== Introduction.

The following Christian experiences of Mary Peisley, falling into my hands,
I thought well to collect and put them into order for the perusal of others.

She led an exemplary life, being watchful over herself,
and zealous for the prosperity of Truth; her mind was so much to its centre,
and her attention so inward, that she often drew others, by her awful sitting,
into silence in Friends' families; and as her cup overflowed,
she ministered to them as one having authority; so that it may be truly said,
she was fervent in spirit, serving the Lord.

Ample accounts have been received of her services in both England and America,
in which the Lord was pleased to bless her labour, and sanctify it to many.

She mourned for the obvious declension of our Society
from its primitive simplicity in manners and conduct;
often declaring that before it shone again in its ancient beauty,
the rubbish must be removed;--that there must be
a division between the precious and the vile,
those who served the Lord, and those who served Him not; but that before this day comes,
greater degrees of darkness would prevail amongst us as a people,
and more of the night come upon us before the day of
beauty and reformation would again revive in splendour.

And therefore she was fervently engaged,
that the faithful every where might stand upon their watch,
and discharge themselves as watchmen and watchwomen upon the walls of Zion,
having their armour on and their lights burning, to be able to discover,
as well as oppose, the approach of the enemy.

The latter part of her time she was attended with much bodily weakness and indisposition,
which often rendered her unfit for travelling;
these she called visitations of the mercy of God to her soul,
in order to preserve her to Himself,
and stain the beauty and glory of this world in her view;
that her affections might be weaned from terrestrial objects,
and fixed upon those things that are above--permanent and enduring to all eternity.

That the perusal of the following experiences may be blessed,
and that the footsteps of this handmaid of the Lord may excite
and encourage all to press into the path of self-denial,
the sure way to sanctification and the rest of the righteous,
in which she delighted, is, reader, the fervent desire of

Your well-wishing friend,

Samuel Neale

