== Chapter I

Mary Neale, late Peisley,^
footnote:[Mary Neale died only three days after marrying Samuel Neale,
and so is best known by her maiden name, Mary Peisley.]
was the daughter of Peter and Rachel Peisley, and was born in the year 1717,
at Ballymore, in the county of Kildare, in Ireland.
She was educated in the Society of Friends; but a disposition to keep company,
unrestrained by the cross of Christ,
led her from Truth`'s simplicity in manners and behaviour.
On reviewing her early life, she thus expresses herself:

"`I count it an infinite mercy and high favour,
that the omnipotent God allowed not the thread of my life to be cut,
during the many years that I lived in disobedience to his holy will;
and though often by the operation of his grace
inwardly touched and convicted of my errors,
and the veil so far rent from off my understanding,
as to let me see that I stood on the brink of ruin,
yet I did as often allow the enemy and adversary of my soul again to
darken my understanding and benumb my spiritual feeling;
and the tumultuous noises,
pleasures and allurements of this world stifled
the intelligence of the still small voice,
which would have directed me, saying, '`This is the way, walk in it.`'
Our meeting also was favoured with a living and powerful ministry, which I often slighted.
Thus have I, with my hard and impenitent heart, stoned his prophets;
and by my unbelief and uncircumcised spirit,
persecuted them that were sent to declare and proclaim the glad tidings of the gospel,
to invite and call to those who were in captivity, held by the chains of sin,
to come away to the glorious liberty of the Truth.
I have to remember, as an inexpressible favour and mercy to my soul,
that in the height of all my vanity and stupidity,
I was not permitted to run into the gross enormities of
the world;--I was kept from those loud,
crying, hardening, black crimes, which had I run into,
might have so highly provoked my Creator, as to have caused Him to say in his wrath,
'`You shall not enter into my rest.`'

"`A short time before my conversion I had a fall from my horse,
by which I was apparently in danger of having my neck disjointed,
and a sudden end put to my life.
As soon as I arose on my feet and recovered my senses,
the Lord by his grace and good Spirit showed me clearly
that I was not in a fit condition to meet Him,
the just and holy Judge of heaven and earth;
and caused me solidly to consider the dismal
consequence of being hurried off the stage of mortality,
in an unprepared state; the impression of which never left my mind, until God,
by his grace,
had made me more fit for his kingdom;--the glory
of which be given to his everlasting name.`"

About this time two Friends in the service of Truth appointed
a meeting within the compass of that in which she resided.
Their awful reverent sitting before the Lord, waiting upon him for his presence and aid,
struck her in an unusual manner;
and raised in her mind a fervent inquiry after
the revelation of the Father through his Son.
She had often heard of the comforts of the Holy Spirit,
the instruction of the light that comes by Jesus Christ,
and the way of spiritual worship:
but she still remained a stranger to the true manner of
seeking and breathing after it in her own experience.
She has expressed how deeply her mind was affected,
by the silent and humble waiting of the before-mentioned Friends,
and by the operation of the universal spirit of grace shed in her heart,
so that she was aroused to inquire for herself;
and as she pressed to wisdom`'s gate her seeking mind was satisfied.

During this dispensation of inward inquiry,
she was helped forward to diligence by the ministry of some of the Lord`'s messengers,
who spoke comfortably to her state,
and encouraged her in perseverance and well-doing,--speaking prophetically,
that the Lord would raise up in that meeting some,
who should bear his name among the gentiles,
and be messengers of peace and glad tidings to the people,
if obedience and faithfulness to the heavenly manifestations were kept to.

By a humble resignation to the Divine will,
forming the vessel in what manner the heavenly Potter pleased,
the work went forward prosperously.
She appears to have been an instance of great fervency and
devotedness to whatever the Divine influence dictated,
watchful to hear the voice, and obedient to fulfill the command,
though it might be in giving up that which was as a right hand or a right eye.

She left in writing "`A commemoration of the mercies and tender
dealings of the Lord`" towards her at this early period of her life,
when, as she stated,

"`He saw fit to divest me of all things here below, that were near and dear to me,
and left me no inheritance on earth but his own Providence; and like himself,
when in the prepared body, and his immediate followers,
he made me to have no certain place of abode:
yet did he raise up friends for me where I least expected them,
and when I was deprived of the care and help of my natural father and mother,
he became a Father to me,
and made others willing to act for me as though I had been their own offspring;
and no sooner did one friend seem to fail me,
but there were others raised up in a fresh quarter,
where he would have my lot to be cast.
Thus as a child was I given up to be disposed of according to his good pleasure;
but my stubborn heart would often rebel against him,
and presume to enter into expostulations with him, and reason with him thus:
'`Why am I come into this situation?
Why receive I your blessings at a second hand,
and must thank my fellow mortals for all the temporal good I receive?`'
Thus ungratefully did I upbraid and murmur against my kind Benefactor,
which drew down his wrath and displeasure,
and caused him to hide his face and leave me to the buffeting of the enemy,
who would have had no mercy on me,
had not the ever-merciful God limited him and shortened his chain.
Thus did I by times count myself the most miserable of all creatures,
bereaved of all inward and outward comforts.
The sorrow and anxiety of my soul were unspeakable, yes,
inconceivable by all that had not felt the like.
But the Lord tried me if I would walk by faith and not by sight,
follow him through bushes and brambles, and in an untrodden path,
to see if I could embrace religion with all its rigors and discipline,
without its soul-supporting consolations;
to see if I could love and follow him for the
favours I had received without hopes of future:
or if I could live on the commemoration of his beauty and excellency
when he had drawn as it were a curtain between my soul and him,
so that no ray of light pierced through to my benighted soul.
Yet at times I was sensible the Divine Arm was underneath, though invisible,
which kept me from sinking into the pit of despair;
even that hand of power that was reached to Peter when he began to sink in the storm,
when he ventured to walk on the seas.
During the time of this my probation,
there was made me an offer of a place in a worthy
family in the neighbourhood where I lived,
which seemed to be much to my advantage as to the outward:
this led me to seek counsel of the Lord, and to desire his direction in this undertaking.
After having weighed it in my mind in the best manner I was capable of,
I found freedom to make trial of it for a time,^
footnote:[At the widow Ann Strangman`'s, of Mountmellick.]
where I was received with all possible kindness and respect,
and lacked nothing this world could afford:
but I lacked the consolation of my Beloved and the light of his countenance;
all other enjoyments were embittered to me,
and lacked the relish they otherwise would have had.
And this I found to be a trial to me,
to see if I could rest in the creatures without the Creator; which I could not do,
blessed be the name of my God;
who had opened an eye in me that could look beyond this world,
and gave me to see the emptiness of all things here below, unless he filled them,
and the danger that was in them, unless he sanctified them to us.
This made me resolve I would not enjoy them without him,
which brought upon me a great conflict and warfare between flesh and spirit.

"`Having left my former place of settlement,
I had no place to go to but my father`'s cottage,
which was very mean to what I had ever been used to: but this I resolved,
by the blessing of the Lord, I would not endanger my soul,
let what would become of my body.
The seeds of ambition and self-love,
which I thought had in a good degree been bruised to death, began now to struggle,
and powerfully to exert themselves against the pure, lowly, humble Seed of life;
and all they needed to overcome was, that my will should join with them;
which the ever-merciful God kept me from, and raised strong cries in my soul to him,
that he might be pleased to give me victory over my grand enemies, the flesh, the world,
and the devil.
And he was graciously pleased to hear and answer my petition,
and have regard to my tears and sighs,
and brought up his own royal Seed into dominion in my soul;
and so he bruised the serpent`'s head, that every thought, wish,
and desire of my heart was brought into perfect subjection.
Then could I say in truth and righteousness, and in sincerity of soul, '`Not my will,
but yours be done, O! God: let me possess this quiet habitation,
this peaceable and happy state, and divest me of what else you see fit beside.
May I be secure of your love and favour,--it suffices me;
let worldly-minded men laugh at my folly for denying myself and the world;
I can pray for them and pity their blindness.`'

"`Thus did the Lord in matchless love cast into the ocean of annihilation,
these passions which, had they been permitted to reign,
would have made me unhappy here and miserable hereafter.
Now was my father`'s humble cottage become so pleasing to me,
that I did not envy the greatest monarch on earth;
nor would I change with them if I might.
How would the Lord often raise my heart in humble thankfulness to him,
in that he fully supplied the demands of nature;
and everything that would gratify a haughty aspiring mind, he as kindly denied.
When I had a leisure hour to meditate in the fields,
behold the fowls of the air and the beasts of the field,
how contented thought I they are in their present state,
who are to have no happiness but what they receive here;
it teaches me that whatsoever station or situation in this life.
Providence has been pleased to fix me in, I ought to be fully satisfied,
seeing he knows best what is good for me,
and that I only crave a passage to endless felicity.
And when I find in myself that capacious mind which cannot, like the brute animals,
rest satisfied with the enjoyments of this low creation or the gratification of sense,
it helps to confirm me, that there is a part in me that was made for Divine enjoyments,
and which struggles to be released from this cage of clay,
that it may come to the full enjoyment of that,
of which I now have but glimpses and tastes.
When I behold the innocent fowls of the air fly from bush to bramble, wander up and down,
carefully seeking every lost grain, the worms, little insects and wild fruits,
for the sustenance of nature,
it convinces me that I ought to labour willingly with my hands,
and not to be a burden to the creation; seeing that my limbs were formed for activity,
and that Adam in his angelic state, or state of innocency,
was to dress the garden and to keep it.
How freely now could I relinquish popularity and vain applause,
which the generality of mankind have such an insatiable thirst
after! but I am sensible there is no having general applause,
without envy and calumny;
for there is a set of mortals so wrapped up in pride and self-love,
that they cannot bear to hear any one well spoken of but their own dear selves.
And besides this, it is a dangerous breath of air which cherishes vain glory`'s root;
it will never waft us to heaven, but rather clip the wings of towering virtue.
On these considerations, I cried from the bottom of my soul, '`O! my God,
give me the thorough knowledge of you and of myself,
let me possess a mind rightly cultivated, with all my passions in subjection,
and a total resignation of my will and purposes to your holy will, a mind truly humbled,
satisfied with few things, filled with humble thankfulness;
let me thus enjoy my happy and innocent solitude, and I shall not envy, nor desire,
the glory of this fading, perishing world.`"

[.signed-section-signature]
Mary Peisley

Her entrance into the work of the ministry was about the beginning of the year 1744,
near which time she had unexpected domestic trials, which brought her very low in mind,
from a sense of the singularity of her situation; but her trust being in the Lord,
she was eminently supported.
About this period she wrote thus to a friend:

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend.

"`I doubt not but you are touched in some degree with a sense
of my deep and heavy afflictions which are of various kinds.
Many are the probations which I have passed through, and still am under.
I can by no means set forth the wise, prudent and merciful manner,
in which my tender and heavenly Father has dealt with me;
by fortifying my mind beforehand,
and likewise in supporting and upholding me under my trials.
In the infiniteness of his wisdom and boundless mercy,
he stained the beauty of this world in my eyes, wiped off the varnish and gilding,
and let me see before they were snatched from me, that they were but momentary,
fading enjoyments; and the greatest and best of them were but short-lived blessings,
and shadows that would vanish away.

Neither did his kindness end there, for he likewise showed me what was substance,
the pearl of inestimable value; at the sight of which my soul was so transported,
that I cried out in an ecstasy of joy, '`Cause me, Lord, to possess this treasure,
and for the sake of it divest me of whatever seems good in
your sight;`'--this was my covenant with the King of kings.
So great was the goodness of my God, dispensed and proportioned in wisdom,
that he did not at that time reveal himself to
me in so full a manner as he has since done,
at a time when I most of all wanted it.
In my deepest plungings he has caused my soul to taste of joys and consolations,
to which I was before a stranger.
Nor would I have presumed to ask for the favours of
patience and resignation and fortitude of mind,
which he has undeservedly bestowed on me an unworthy creature.

[.signed-section-signature]
Mary Peisley

--

An opportunity presented for her to reside in the family of a Friend,
within the compass of Mountmellick meeting, of whose daughter she had the care.
In this station she continued for some time,
until she apprehended herself thereby deprived, in some degree,
of a full liberty to exercise the gift received, and to live to Him alone,
who had quickened her anew in Christ Jesus.
She wrote thus to a relation at this period.

[.embedded-content-document.letter]
--

[.letter-heading]
To her Cousin

[.signed-section-context-open]
Edenderry, 2nd of Second month, 1746.

[.salutation]
Esteemed Cousin,

After the salutation of dear and unfeigned love,
I may inform you that by the wonderful mercy of Providence I enjoy health of body,
although I have been of late in the midst of infection,
and have suffered more hardship by constant care and labour, than I ever knew,
I suppose that you have heard that I have been for some time past at Ann Strangman`'s,
where several of the family have been ill of a fever;
so that it unavoidably fell to my lot to be assisting at that time,
as it so fell out that all the women servants were ill at one time,
and others of the family; and before that happened,
I was not without a large share of trouble and care,
I being entrusted with the care and oversight of the family,
which I find to be a great load and oppression to my mind,
and a hindrance to my spiritual warfare, which I think far worse than my bodily hardship.
But I am come to this result in myself,
that if Providence do not make way for my task to be more easy, that I will quit it,
as I am not bound to it: for I am resolved by the blessed assistance of Israel`'s God,
not to bury that talent which he has given me (in the earth,)
nor to quit the occupying of it for any outward employment.

Better would it be for me to wander, as the prophets formerly did,--destitute,
distressed and naked, than to sell an unfading inheritance,
for any prospect of advantage here.
For I am sure, to drudge for the sustenance of the body, as do the beasts,
and to live for no nobler ends, than to eat, drink and sleep,
such a life is not worth living for: not that I am against moderate honest industry,
for I am convinced it is good for both body and mind;--but I never
experimentally knew the hurt and danger of inordinate care as at this time.

[.signed-section-signature]
Mary Peisley

--

About this time a concern attended her mind, to visit Friends of the three provinces;
this she pretty generally performed in company with Elizabeth Tomey of Limerick,
in sweet unity and concord.
They met with low times and seasons, deep baptism of spirit;
they travailed for and with the seed,
and at times were set at liberty in the authority and power of Truth,
to minister to the various classes of the people.

Of the quarterly meeting of Ulster held in Lurgan, she gives the following account:

"`We attended the meeting of ministers and elders, where we had close work;
but the power of the Lord upheld us above the fear of man.
Next day had some encouragement to the faithful and well-minded,
but could not that day reach the libertine spirit;
however we waited for renewed strength from the Lord, to engage against the Goliaths,
who defy the armies of the living God.
The day after being first-day, we sat in a low humble depending state,
until the Lord gave the spirit of supplication; after which his power was set over all,
and testimony was borne to his name, and transgressors were shown their errors,
in the demonstration of the Lord`'s Spirit and power.`"

After this journey she went to reside with a relation at Borris in Ossory,
from which she writes as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To a Relation

I am at times concerned for the whole bulk of mankind,
but in a more particular manner for my kindred according to the flesh,
and especially those who were my companions in my former vanities,
as well knowing what the life I then led would have ended in, had not my God,
in his infinite mercy opened my eyes, and stopped my race to ruin;
and though I was in the broad way that leads to destruction, yet was I innocent of,
and free from the gross enormities that are in the world;
and because thereof the enemy persuaded me that I was safe enough.
But alas!
I found I was living as without God in the world, in forgetfulness of him,
a stranger and unregenerate; in short, that I was an enemy to God,
and under his just wrath and displeasure.
And now I may say, that I am jealous with a godly jealousy,
that you are yet in that unregenerate condition.

You will say, perhaps, you are not called to the same work that I have been called to,
that is, to the work of the ministry, and have no need to know what I have experienced.
If this should be suggested to your mind, it is of the enemy;
for if you have not been called to bear a public testimony,
you have I doubt not been called to holiness, without which we are told,
"`no man shall see the Lord.`"
You have the same pure holy God to fear, the same subtle unwearied enemy to war against,
a soul as precious, and which must abide as long, as mine, either in happiness or misery;
therefore it behooves you to be as strict in your life,
and as holy in your conversation as any other;
that so you mayst be a terror to evil doers,
and a praise and encourager of them that do well.
For I am sure if we be lovers and true followers of Jesus,
we cannot take pleasure in hearing his great name profaned, and taken in vain:
and their company that are guilty of such things we should carefully avoid,
as we would an infectious person.

It is, I think, impossible to be frequent in ill company,
without being somewhat leavened into the same spirit, except we keep a strict watch,
and have our minds armed with the pure armour of light and righteousness.
This alone can make us proof against the fiery darts of the wicked,
which insensibly pierce and wound the unwary soul.
It is our interest and duty, all in our power, carefully to avoid temptations,
for those that we must inevitably meet with, are enough for us, poor weak creatures,
to grapple with.
Take care of poisoning your mind with vain and idle books, for I know them,
by experience, to be very pernicious;
let your leisure hours be spent in retirement and reading the Holy Scriptures,
with other good books.
Remember you are the head of a family, and it behooves you to have a superadded care,
for if your example be not good, you will have much to answer for.
Watch over your sisters in love,
and be not an instrument of bringing evil company in their way.

There is an evil that you are guilty of, which is visible to more than me,
and that is your slighting and neglecting week-day meetings.
If you had appointed a day to meet any of those styled noblemen of the earth,
and you slighted and neglected the appointment for weeks, yes, months together,
would it not be a great affront and indignity to them?
Yes; and I am persuaded you would not do it, for fear of offending them;
and is the King of kings and Lord of heaven and earth, less noble, less discerning,
when He is slighted and neglected?
I observe you have time and leisure to ride many miles to sports and diversions,
such as hunting, horse-racing, and other sights;
does not this show you are a lover of pleasure more than a lover of God,
such as the apostle declares are "`dead while they live.`"
Dear cousin, bear with my dealing thus plainly; I have no view in it,
but the good of your immortal soul, and the ease of my own mind;
and I sincerely wish that you and I may be prepared for our great and final change.

We have daily instances of the young and the strong being snatched
away in their bloom as with their bones full of marrow:
and why may it not be our easel we cannot promise ourselves one hour to come;
the present time is only ours;
and O! it is a dismal consequence to launch into eternity unprepared,
where the worm never dies, nor is the fire quenched.
If we are so fond of a few transitory pleasures in this world,
how can we bear to be shut out from eternal felicity, and doomed to everlasting misery?
I beseech you solidly to consider these things,
and I pray the God of love and mercy to give you a wise and understanding heart.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Abigail Watson

[.signed-section-context-open]
Borris, 6th of First month, 1747.

[.salutation]
Esteemed Friend,

I received your kind epistle of the 6th of last month:
I am thankful to the Lord that He caused you to remember me.
You desires me to bear with you;
I would be very sorry to be in that mind in which I
could not bear counsel or admonition from the least,
meanest or youngest of the Lord`'s servants,
who would do it in the spirit of love (as I am well assured you have done),
much less from you, whom I look upon as a well-trained, disciplined soldier,
on whom the Lord has put his armour and sent forth in the spiritual warfare,
and have known the wiles and subtlety of that grand
enemy;--one that has seen the mystery of iniquity,
as well as that of godliness;
which lies hid from all but those whose eyes the Lord opens.
Such a one is surely fit to instruct a poor, young, raw, unskillful stripling as I am,
and I will freely confess a coward too;
for if my Captain does but a little withdraw Himself, I am ready to say with David,
I shall one day fall by the hand of my enemy.
Therefore I would beg of you to remember me, when it is well with you.
It was not to please the ears of men that I first became a fool;
nor are men to be my rewarders; it was for the sake of that peace,
which the world can neither give nor take away; and for this do I still strive,
and hope by Divine assistance I shall ever prefer before all other things.

I would have you and all my friends be free in speaking or writing to me,
as Truth opens to you; for I doubt not but I have need of counsel,
and to be stirred up to my duty; for I think myself far short of what I ought to be.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Strangman, Mountmellick, on the death of her husband.

[.signed-section-context-open]
Dublin, Third month 14th, 1747.

[.salutation]
Dear Friend,

This goes with a salutation of unfeigned love to you,
with whom I truly sympathize in your present affliction.
Yet you have not cause to mourn, as one without hope;
for your late companion has left behind him a sweet
savour in the minds of many of the sensible;
and he being dead yet speaks, and his memory will live for generations to come.
But this is your greatest joy, that you have been made acquainted with,
and your soul espoused to Him, who can never be snatched from you,
while you are willing to cleave to Him.
He who has promised to be a husband to the widow, will I am persuaded be so to you,
and doubly make up the loss, by a superadded degree of His own Divine presence,
as you are resigned to His holy will in all things, which is our reasonable duty.
All His dispensations are for good, though we are so short-sighted,
and His wisdom is so deep, that it is many times beyond our comprehension.
This is certain, that no afflictions are joyous for the present, but grievous;
but as we know the Lord to sanctify them to us,
they will work for us "`a far more exceeding and eternal weight of
glory:`"--such I hope and believe yours will prove to you.

And though your trial is great,
you are yet favoured above many in being blessed with a fine offspring,
who at this time look promising to be a comfort to you;
and you are sensible the Lord has visited and reached to some of them in a near manner;
and has so replenished you with the things of this world,
that with His blessing you need not fear need or penury.
But above all this, is to be prized, that the Lord has given you a heart,
which I believe more strongly desires for yourself and children an inheritance in Christ,
than all outward enjoyments;--that both may be added to you, used in His fear,
and to the glory of His name who gives them,
is the sincere desire of your sympathizing friend.

[.signed-section-signature]
Mary Peisley.

--

About the eighth month, 1747, she returned to Mountmellick,
to the house of her friend where she before resided.
Her continuance at this place was but for a few months,
during which time she was attacked with a disorder in her stomach,
which occasioned great weakness, and brought her very low.
In a letter to a friend she thus expresses herself.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

I gratefully acknowledge your unmerited kindness in the concern you show for my health.
I am sensible it is our indispensable duty to endeavour to preserve life and health,
by all lawful means that Providence is pleased to afford; were it not so,
I often think that mine is not worth caring for.
Instead of being useful to any, I fear I shall be a burden to the creation,
and miss the end of my being.
Surely none whom he has sent into life, and visited with His matchless love and kindness,
is more weak and unworthy than I am; and were it so that He, by his divine power,
was pleased to make use of me in any good work, it was all His own,
of and from Him alone; I could have no part in it, but as passive clay in his hand.
And blessed be his name.
He is not limited, nor his power confined to any instruments.
He that found me in a polluted state,
can raise up and sanctify many more for his work and service,
and that he may do so in these dark and perilous days,
is the travail of my afflicted soul.

[.signed-section-signature]
Mary Peisley

--

During this dispensation she wrote as follows to her brother,
who had frequently occasioned much anxiety and disquietude to her mind.

[.embedded-content-document.letter]
--

[.letter-heading]
To her Brother

[.salutation]
Dear Brother,

For so you are by nature to me;
would to God you were so in a two-fold sense, that is,
by adoption or new creation in Christ,
which far exceeds all the ties of affinity or consanguinity,
and will last beyond the grave, never, never to be dissolved.
Mayst you happily experience this, before time to you here be no more;
for which end Providence has, in matchless love and condescension,
wonderfully prolonged your days, amidst imminent dangers and difficulties.
May this be deeply pondered and wisely laid to heart by you,
otherwise it will add weight in the balance against you,
in the great and notable day of account, that hastens on us both.
You know, dear brother,
it has often been my concern thus to remind you
concerning the important business of life,
and your neglect of it has almost discouraged me from further attempts:
this may perhaps be the last; and I do with all the ardency my soul is capable of,
joined with natural affection, earnestly desire that it may have the wished for effect.

I am in a very poor state of health,
and with little human probability of my being restored.
My disorder is attended with acute pain; but blessed forever be the name of my God,
patience equivalent thereto has been administered.
How it may be with me as to life or death, I cannot say;
but this is my greatest consolation,
and such a one as is beyond the power of my tongue to express, or pen to set forth,
namely, that I have not spent my health and strength in the gratification of my passions,
or sensual appetites, but in some degree in the pursuit of that which now stands by me,
and will go with me beyond time,--a good conscience towards God;
whose love I feel to flow in my soul in such a manner,
as to admit of no doubt that He is my friend,--or in other words, that He is in me,
and I in Him, and will be so to all eternity, if I forsake him not.
Believe me, brother, when I tell you, at a time when dissimulation must vanish;
at a season when we are best capable of knowing ourselves,
and judging of all things in the clearest manner,--when
the mists of the world are removed from before our eyes,
and eternity presented to our view,--at such a time as this I may tell you,
I am not afraid to die; nor is the sound of mortality and eternity frightful to my ears.
No; I cannot look on death as a king of terrors, but as a welcome messenger,
who comes with a happy release from all my trials, temptations and afflictions,
to summon me to an eternity of unmixed felicity,
to that which I have most loved and delighted in for years past,
though favoured with but a glimpse and foretaste of it,
while my soul is loaded with its companion, flesh;
but what will it be when the face of the Divinity will be forever unveiled,
faith turned into vision, and the full fruition come to?
These are words of truth and soberness.
I know there is a kingdom of heaven, because I already feel it within me,--Christ in me,
as said the apostle, the hope of glory; and because he lives,
I live also;--not merely an animal life which must perish,
but a life hid with Christ in God.
Without a new creation in Christ, it is impossible for us to enjoy God; or,
in the words of his Son Christ Jesus, to see or enter the kingdom of heaven.
Had we not bodies taken from the earth it would be
impossible we should enjoy or live by the same;
and if we have not a new birth begotten or formed of God in us,
it is likewise impossible we should live to or in Him.
More I might say, to illustrate this important truth to your understanding,
if bodily strength would admit;
but unless you center down in true sincerity and
humility to the pure light of Christ in yourself,
by which alone what is to be known of God is manifest in man, these things,
with all the other truths of the gospel, will forever remain a mystery to you,
as it has done to ages and generations, and to the wise and prudent of this world;
but is revealed unto the babes,
that are begotten and born of the incorruptible Seed and Word of God.

I conclude your affectionate sister in the hope, and O! that I could say fellowship,
of the gospel.

[.signed-section-signature]
Mary Peisley.

--
