== Chapter II

About this time she felt a weighty concern to visit the churches in England;
and having obtained the concurrence of her friends, accompanied by Elizabeth Hutchinson,
she set forward from Mountmellick in the seventh month, 1748.
They attended the Province meeting held at Carlow, and went from there to Baltibois,
where they had a blessed helping meeting.
The testimony went forth to those of other societies.
They had a meeting at Timahoe, and went from there to Dublin;
where they had refreshing and comfortable meetings,
the Lord's eternal Truth being over all.
"`We were,`" she expresses in a journal kept of this journey, "`comforted one in another,
and enabled renewedly to bless the name of the Lord.
The 27th of seventh month, we took ship for Whitehaven, and landed there on the 28th;
on the 30th we went to Pardshaw, where was held the quarterly meeting for Cumberland:
the public meeting proved a glorious one, and was a time of solid worship;
the testimony of truth was exalted over all, and the everlasting gospel freely preached.
After this meeting I had great consolation of soul,
and we spent the evening in company with several Friends,
in agreeable edifying conversation, and in much freedom and openness of spirit.
Next day, being the first of the week, we went to their general meeting at Cockermouth;
on the 3rd to Whitehaven, low and depressed in spirit.

Next day had a meeting there, in which I cleared myself;
I was led therein to set forth the call and qualification of a true gospel minister;
left it in peace of mind, but was much spent in body with the service thereof.
The 5th, had a meeting in Broughton,
where we were led to speak closely to some who had been visited in their young years,
and were now grown lukewarm and indifferent.
The 6th, had a good meeting at Isell, though small.

Next day were at Keswick, the service chiefly to those not of our Society;
had some close things to deliver to those that were.
The 9th, at Allonby, where came many Friends from other meetings,
to whom Truth was freely declared.

From hence to Holme, where we had a silent meeting,
and understood they seldom sat free from disturbers.
The 10th, had a low season at Kirkbride, the 11th at Bolton, the 12th at Wigton,
which was large but low as to the dominion of life; next day at a meeting at Moorhouse,
we had things close and hard to deliver.
At Carlisle we had a good open meeting, my mind being much enlarged amongst them;
yet I felt a concern rest with me to have another meeting in that city,
which Friends readily agreed to.
On the 15th, we had a meeting at Kirklington, which was large and satisfactory;
and another at Carlisle in the evening, in consequence of the concern already mentioned,
to which there came a great number of town's-folk.
When I got there I found myself so weak in body and poor in spirit,
and the people so unsettled in their minds,
that I almost feared I should not be able to answer the service of the meeting.
I earnestly desired that the cause and testimony of Truth might not suffer,
let me suffer what I might.
I had not sat long, before I found a flow of doctrine open in my mind;
I stood up in the fear of the Lord, and the people soon became quiet and solid.
I was strengthened beyond my expectation, and the meeting ended well;
and blessed be the name of the Lord,
I had great peace and satisfaction after it was over.
Went from there to Scotby, and had a meeting; so to Ann Grenup's,
and was at the monthly meeting in that quarter, where my mind was under much suffering;
but as I waited, the power of Truth arose, and I found ease and liberty of mind;
was led in a very close manner, the Seed had dominion,
and the authority of Truth was over all.
Went next day to Mosedale, and had a travailing season in that meeting;
from there to Terrill, and had a poor meeting there; from there to Isaac Thompson's,
being very poor in spirit and low in mind.

Next day we rested, spending the day much in retirement, which proved very helpful to me:
and as I waited on the Lord to have my spiritual strength renewed,
I felt a concern to have a meeting with the inhabitants,
and one in the afternoon at Penrith on first-day.
After I had well considered and weighed these things,
the Friend with whom we lodged said, they were a people of no religion;
which did not discourage me, for it immediately arose in my mind,
that they had the more need of help, and that, perhaps,
they might more readily receive the Truth,
than those who were more bigoted to ceremonies.
We went to Penrith next morning,
when the Friends asked me if I would have an afternoon meeting;
I replied that I could better tell at the conclusion of the first meeting.
We went to meeting, and it proved a good one, for Truth had dominion and was over all.
Then I felt strength to have an afternoon meeting appointed,
which was large and to great satisfaction;
some of the town's folks being at the forenoon meeting, and the town pretty large,
the report spread,
and the people came until the house could hold no more with convenience.

After this I spoke of the meeting which my mind was drawn to propose at Amenbridge,
where a Friend said there had been none before.
Friends seemed willing, but knew of no place to hold it in,
except the house where we lodged, which was large enough,
and would have done well for the purpose, but the Friend said he could not admit of it,
for fear of his landlord, who was a priest.
I said I could not force their hearts nor houses, but hoped,
as I had laid it before them, I should be made easy; and if not,
I did not doubt that if I went to some of those who professed not with us,
I should be accommodated.
He said, there was a town a mile off, that he thought would answer better for a meeting,
and that their town's-people would go there;
I told him I dare not go in my own will to have meetings where I pleased,
but where Truth led me.
He replied, if the folks of Penrith heard of the meeting, the streets,
much less the house would not hold them; then, said I, we may go to the fields.
This, I believe stirred him up; he went away, and in a short time returned,
and told me not to be uneasy,
I should have a meeting:--accordingly it was appointed to begin at
six o'clock next evening at another Friend's house in the town,
which proved quite too small.
They made all the room they could in two apartments and a hall,
but many who could not get in were at the windows.
We had a meeting at Strickland in the forenoon, which had before been appointed.
When I came to see and sit amongst the people at Amenbridge,
they seemed so ignorant of our manner of worship and principles,
that my faith almost failed of doing any service, or administering help to them.
After some time of waiting for Divine aid, I stood up;
and they appeared to me as still and attentive, while I was speaking,
as ever I observed any assembly.
I laboured amongst them until my natural strength failed; and after meeting was over,
I had great inward peace and comfort.
Next day we waited for their monthly meeting at Aldstone,
and paid a visit to a Friend's family, where we had a sweet consolatory opportunity;
and the same evening went towards Northumberland.

"`The 25th of eighth month we continued our journey,
and had a very difficult and dangerous road, much of it mountainous;
and though reckoned but fourteen miles,
it took from nine in the morning till six in the evening,
save that we stopped a little to refresh ourselves;
my mind was preserved tranquil and easy.
Next day we had a hard laborious meeting,
but I was mercifully helped through to the ease of my own mind.
The following day we went to Cornwood, where we had a meeting.
The 27th rode to Allendale, and the way being rough and mountainous, it was dangerous.
My companion was thrown from her horse,
and I seemed in imminent danger,--the way being narrow,
and a considerable precipice just by where my horse stood,
which being interrupted by my companion's falling became very uneasy: but at length,
through the merciful interposition of Providence, she was taken up, very little hurt;
and they got me safe off my horse.
We arrived wearied with fright and fatigue.
In a short time Friends got together, and we had a comfortable good meeting;
which amply made amends for all we went through.
The 28th, we had a large meeting.
My spirit was under deep suffering, before I went to it, and for some time after;
but through Divine aid, I fully cleared myself When I came to my lodging,
I was under a baptism of spirit, and could not tell the cause.
I examined myself, and brought things to the closest scrutiny,
to know whether I had done or omitted anything contrary to Truth,
but could find no condemnation.
At dinner I felt the spirit of supplication, which I gave way to,
and found my mind free and easy.

Next morning, the 29th, set out for Benfield; it was such hard weather,
Friends would have had us stay, but as the meeting was appointed,
I could not be easy so to do.
It blew such a violent storm, that it was with difficulty we could sit our horses,
or they keep their feet, being several times blown out of the path.
It was fourteen miles over a black moor, where there was no shelter;
our guides missed the way twice, once on the open moor.
My companion, who was a young traveller, was discouraged,--stopped several times,
wept and said she thought she could hold it no
longer I encouraged her to hold out to the end,
and told her there was no abiding there.
By the Lord's mercy, my mind was kept quiet and still,
and about seven at night we got safe to our quarters, where we had a hearty welcome.
The meeting was appointed to begin at nine next morning; it was small,
but greatly to my satisfaction.
I was led in particular to some person,
who was under a temptation to join in marriage with one of another society,
and likewise to declare that I had no outward information.

After meeting, an elderly Friend told me that I had hit the mark to a hair's breadth;
for there was a young man, who he knew was under such a temptation,
and had been advised against it.
Went that night to Newcastle-upon-Tyne, eleven miles, stayed there several days,
had a good meeting on fifth-day, being 3rd of ninth month,
though some states were hard to speak to,
there being some deistical principles I believe cherished amongst them;
and so close was the testimony, that they could scarcely bear to sit.
After this meeting, a Friend told me I had spoken by revelation;
but was so prudent as to say no more, as we were to stay until after the next first-day,
to equip ourselves for continuing our journey.
In the interim visited the aged, who were confined from weakness.

First-day, Truth eminently helped with its ancient beauty and brightness,
dispelling all mists and clouds;
a glorious time it was to the comfort and edification of the church.
The afternoon meeting was very full of Friends, and those of other societies;
it proved to me a sweet consoling time,
the spring of life being opened for my own help and furtherance in best things;
but I had not anything to communicate to the people.
On the 6th, went to Shields, and had a small meeting:
from there in the evening went to Sunderland.
The 7th, had a meeting in the forenoon, to an increase of comfort;
praise be to Him who exalts his own testimony in the hearts of his children,
and gives tongue and utterance to magnify his name and power.
Had a refreshing season in the family where we lodged,
the Lord breaking to us the bread of life for the nourishment of our souls;
afterwards we had an evening meeting appointed, which was large and to good satisfaction.
The 8th, had a meeting at Shotton; the 9th, at Durham; the 10th, at Auckland,
which last was a good meeting.
I felt a concern to have another there in the afternoon,
of which I acquainted the Friend with whom we lodged; he pleaded many excuses.
I told him, I apprehended it was not the business of a minister,
to proceed contrary to the minds of Friends, especially one so young as I;
and that as I had mentioned my concern, I hoped I should be easy; if not,
I could but come back again.
My mind was soon relieved of its burden;
as the Lord my God knew my willingness to obey him, he required no impossibility of me.
Next day went six miles to Raby, had a large meeting there,
several Friends coming from various places to meet us; but that spirit was amongst them,
that obstructs the spring of the ministry, and made it hard to speak;
yet by Divine assistance, I was enabled to clear myself,
and came away with peace of mind.
My companion was so ill that she was detained from meeting two days.

"`On the 13th, we went to Lartington meeting, and returned in the afternoon;
next day to Darlington, and had a meeting there on the 15th; it ended well,
though hard in the beginning.
The day following went to Stockton; had a full meeting and came away in peace.
The 17th, had a meeting at Yarm; it was small, several young people came from Stockton,
and it proved on the whole to good satisfaction.

Next day, was at a small meeting, where I sat a pretty while in silence,
and a state of mourning for the cause of Truth.
I eased my mind amongst them, and came away in peace.
On the 21st, had a meeting at Gisborough; and 23rd, at Mooresome.
The 24th, was at the monthly meeting held at Castletown, where were many plain, honest,
sincere Friends, and we were comforted in the Lord and one in another.
Next evening at Hinderwell and Roxby.
The 26th, went to Whitby, and that evening had a meeting with several Friends,
who came to see us.
Next day, attended a large meeting; my spirit was under great suffering,
and continued so until the afternoon,
though I had delivered in the forenoon meeting what appeared to be given me;
but in the afternoon the power of Truth was in dominion,
and every opposite spirit made subject; things were spoken to closely and clearly,
and Babylon threshed as with a sharp instrument, that she could not get from under.
Then was my spirit made easy, and my soul rejoiced in the Lord, who is worthy;
and prayer, praises and thanksgiving, ascended unto Him that lives forever.
Had the company of several Friends this evening, which was spent in, I hope,
profitable conversation.
The 28th, had a meeting at Stentondale.
The Friends in this quarter are but few, I think eight families composed the meeting;
it was with these few a memorable season of humbling gladness.

"`Came to Scarborough in the evening of the 28th,
and next day had a large and satisfactory meeting.
In a Friend's family where we spent the evening, had a reaching affecting season,
manifested by much brokenness of spirit.

The 1st of tenth month, had a meeting at Fickerington; and the 2nd at Kirbymoorside,
which was large, and attended with the going forth of some seasoning instruction.
Went after meeting to John Richardson's; he is near eighty-four years of age,
a man very remarkable for sweetness and liveliness of spirit, full of love,
clear in his understanding, and his memory strong.
He sat up till late with us, relating the wonderful dealings of the Lord with him,
which was truly edifying, and such as I had never heard before.
He was quite open with us, which I looked upon as a favour from the Lord;
I wept much at parting with him, and when we took leave,
he desired the Lord might bless us.
Next day went to Malton.
The day following, had a large meeting,
and passed through a laborious exercise amongst them.
The evening was spent to spiritual profit, in waiting for a renewal of strength,
and imparting some of the bread handed to my soul to others,
whom I visited in their families; left this place with peace of mind.

"`On the 6th, I was at a monthly meeting at Bridlington; it was a season of suffering,
my mind being very low after it, which caused an examination,
but finding nothing to accuse myself of, was made easy.
The 7th, we were at Hornsea meeting; the Lord's eternal power broke in upon us,
to the comfort and refreshment of our souls, and it was a time of solemn worship.
Next day we were at a meeting at Oustwick, to our great comfort and solid refreshment.

The 9th, at Eastend.
The 10th, had an evening meeting at Hull to profit and edification,
through the aboundings of that life which enlightens and sanctifies.

"`On the 11th of tenth month we went to Beverly, a town where no Friend lives,
having felt a particular draft to have a meeting there;
several Friends from Hull attended,
and the people flocked in until the house was nearly filled.
I stood up and began to speak, but people rushed in so,
that I was under the necessity of stopping until they were settled; I then proceeded,
and a glorious meeting it was,
the Divine power and authority of Truth commanding silence throughout the multitude.
Next day we went to visit a few at Skitby, who were lately convinced,
with whom we had a good meeting, and some open, profitable conversation.

The 13th, we went to Northcave; Friends from several parts adjacent came there,
which made the meeting large, but not open and lively; we had hard labour,
yet it ended pretty well.
The 14th, had a meeting at Howden; there were but few Friends,
and some of the town's-people; who being in the Ishmaelitish, mocking spirit,
the true Seed did not reign amongst them.
The 15th, were at Ratcliff; the 16th, at Thorn; the 17th, at Braithwaite; and the 18th,
again at Thorn.
These meetings were generally small, and low as to the life of religion,
which caused laborious work for us to get down to the Seed,
so as to minister to the states of the people.
The 20th of tenth month, had a meeting at Beltoft, which proved satisfactory;
some who were not of our Society attended, who were very solid and attentive;
some were tendered, and several came in the evening,
with a desire of having a meeting with us; but feeling no concern for it,
I could not encourage it.
On the 22nd, visited the meeting of Blyth in Nottinghamshire, which began at two o'clock.
I was led very closely in it, had to remind them of the practice of our elders,
and told them,
if they would search from where that custom of
deferring meetings until afternoon had its origin,
they would find it was not in the Truth.
The meeting ended well, in the sweet consolating love of the Lord my God.
The Friend we lodged with not being at meeting, but engaged in his shop,
I had some close discourse with him concerning his duty to God;
at first he seemed to put it off, but was brought to acquiesce with what I said.
Next day had a small, but good meeting at Warmsworth; had a loose,
libertine spirit to speak to; which the authority of Truth helped me through with,
to the enlargement of peace in my own bosom, and the exaltation of that power, which,
when it rules, causes the righteous to rejoice.

The 25th being first-day, was at Pontefract meeting, which seemed very weak and dwarfish,
as to the life of religion; their undue liberty in externals,
manifesting that their dwellings were not with the humble Seed,
that crucifies to the world, and tarnishes its beauty: had little to communicate,
yet felt a revival of light and strength to my own state.
I had a concern to have a meeting with those not of our Society; a great number attended,
many of whom were light and vain, but while I was exercised in speaking,
they were mostly quiet and attentive, and I hope the opportunity was to edification.
The 26th, had a meeting at Selby, which was but small.
That evening went to York, and attended the quarterly meeting,
which began at five o'clock; it was a season of travail and exercise to a living remnant.
Next morning at nine, the meeting of ministers and elders began;
when the baptizing power of the Lord was witnessed by the faithful,
and through the succeeding meetings help was graciously afforded,
and the church was edified.

+++[+++Her written memoirs contained particular accounts of
the meetings visited throughout England,
which are omitted for brevity sake,
having given the above specimen of her travels and baptisms;
there is one extract however which has been preserved of her journal,
which is too remarkable to be omitted:
it appears to have been written when travelling in Yorkshire, at Knaresborough.]

Having been under deep baptisms and poverty of spirit,
as I quietly rode along the Lord was pleased in mercy to break in upon my mind,
by his life-giving presence and power; and it became the language of my soul,--'Speak,
Lord, and your servant will hear.'
After which, many things were divinely opened to me, wherein I greatly rejoiced,
and was thankful to the Lord my God.
Then I found a sudden but gentle rebuke, and heard as it were a voice,
that said in the secret of my soul, 'These dispensations you most delight in,
are least pleasing to me and not so beneficial to your soul,
as that pure poverty of spirit, brokenness and contrition of heart,
which bring into humility of mind; and the reason why this is so little desired,
and so unpleasant to the creature, is, because it can have no part therein,
but is wholly and entirely excluded and set at naught--
can discover no beauty or excellency in it;
and this is the reason I love the offering of a broken heart and contrite spirit,
as it is most pure, and without any mixture of the creature.
For, whether there be prophecies, Divine openings, revelations, consolations,
joyings or rejoicings in the Holy Spirit, gifts of healing or tongues or utterance,
in all these self can rejoice and have a share, being obvious to it,
and bringing it honour.'
Then said I, 'Lord dispense to me what is most pleasing unto you, and best for my soul,
so long as my weak faith and patience can endure it; but when I am ready to faint,
give me a little of the wine well refined on the lees, that my soul may rejoice in you,
the God of my salvation.'`"

The following letter was written from Bradford in Yorkshire, 2nd of eleventh month, 1748.

[.embedded-content-document.letter]
--

[.letter-heading]
To Joshua Strangman

A few days ago your acceptable letter reached me at the city of York,
which I read with a mixture of satisfaction and sorrow; satisfaction to find,
that you still retains your love to the Eternal excellency; and sorrow,
that the powers of darkness should still so far prevail,
as to cause such strong struggles of soul, and sore conflicts of spirit, as you write of.
But I have not the least doubt of your deliverance,
and firmly believe your God will magnify and exalt his own Divine power in your soul,
and make bare his holy arm for your salvation, by revealing it in you,
an unfailing preserver in every needful time.
This I write not altogether from myself,
nor from the impulse of friendship and gratitude;
it is from a degree of that assurance and humble confidence,
which Truth has at this juncture communicated.
It is reasonable to think by your conflict, that the time of your release is at hand;
it was so with Israel of old when they were to be brought out of that dark land,
their task-masters were harder, and their burdens made heavier.
I believe there has no temptation befallen you,
but what has been witnessed by your brethren who have trodden the same steps,
even through the region and shadow of death, by the gates of hell, yes,
out of the belly of hell have some called as Jonah did, and He heard them.
His righteous ear is not grown heavy that He cannot hear;
but for the sighing of the poor, and groaning of the needy soul.
He will yet arise; and then it is that all our enemies are scattered,
and one enabled to chase a thousand, and two to put ten thousand to flight.

Though it must be confessed it is a day of darkness, famine and distress, yes,
thick darkness, that may be felt; yet blessed be the name of our God,
he is as a Goshen to his children, giving them light in their habitations;
and setting a mark upon them, who sigh and mourn for the abominations of the people.
You seem willing to give me an idea of your spiritual state and condition,
even by an outward representation; but I think I may say of a truth,
I have both seen and felt it, even by sinking down below all that is of the creature,
to the pure humble Seed of life; where the visions of light are seen,
and the voice of the great oracle heard, distinct from any other sound.
Here have I found you present, in Him who is omnipresent,
and tenderly sympathized with your soul, according to my small measure.
In this do I desire to have our friendship renewed, and fellowship kept stedfast,
which is with the Father, and the Son.

I take kind your seasonable warning to watchfulness, which I surely stand in need of,
in this time when drowsiness and spiritual lethargy have generally infected mankind.
You will, perhaps, like to hear an account of my spiritual progress and travel Zionwards,
and of the states of the churches here, so far as my small sight can reach;
and I may say, it has been a real grief and affliction to my mind, to see the desolation,
darkness and insensibility that generally prevail;
having been made to go mourning on my way, with this language in my soul, "`Lord,
to whom have you sent me?
Where shall I find your flock and family upon earth?
I see very few who like even to hear or speak of you,
and surely if your love had the pre-eminence,
out of the abundance of the heart the mouth would speak, or, at least,
the soul would love to wait in silence for your Divine appearance.`"
But alas! many seem to have nothing further to inquire about, than from where we came?
where we go?
our names or parents, or if we be married?
To which last question I often answer,
I hope I have been honourably espoused to one husband;
but they are quite ignorant of Him whom my soul loves, and of my meaning.
Yet although it be thus, there is a living remnant in this part of the world,
though under great suffering and oppression;
with which I have been made deeply to sympathize,
and have greatly admired the Lord's goodness and condescending love;
his forbearance and long suffering to a disobedient and gainsaying people,
not willing that they should perish.

As to my own particular, I find the truth of that saying of the apostle,
that "`they who preach the gospel, live by it,`" in a spiritual sense;
and though the Lord has been pleased at times to cause his candle to shine upon my head,
and clothe me with his royal robes, yet I often witness, a being entirely emptied,
stripped and destitute almost of daily bread, and have had, as Mordecai,
to go down and sit at the king's gate, all which I see is for my good;
for when a cistern is let dry, the earthy sediment is discovered,
a fit time for cleaning it, that so the water may flow from it with greater purity.
Therefore I strive to learn the great lesson, of being content in all states,
and may say to the praise and honour of my kind Master,
that he has (since I have given up to serve him)
caused his peace to flow in my soul as a river:
whose current is not long to be controlled by
all the impediments which can be laid in its way.
Blessed forever be his holy name,
he has afforded me strength to discharge myself
faithfully and honestly wherever my lot has been cast,
both publicly and privately; so that I have no condemnation on that account,
nor have I ever yet repented leaving all to answer his holy requirings,
but do humbly thank him, that he enabled me so to do;
and were crowns and diadems laid at my feet,
I would not give His approbation for them all,
for it is surely a dreadful thing to fall into
the hands of an incensed and omnipotent Being.

Before I conclude I would say, beware of Esau's crime;
it was when his soul was ready to faint, that he despised his birthright;
when he had been eagerly pursuing something he delighted in,
(I observe it was not the Truth) he came to this unwise conclusion,
"`Behold I am at the point to die, and what profit shall this birthright do me?`"
He lacked patience and solid reflection,
and afterwards had bitterly to repent when too late.
Had he not resigned it none could have taken it from him,
neither can all the powers of darkness, from you, if you resolve to keep it;
this must be done, by cleaving to the Lord with all your heart, with all your soul,
and all your strength, which that you mayst be enabled to do, is my fervent prayer.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel Judd, in Ireland.

[.signed-section-context-open]
Mankinhols, the mountains, in Yorkshire, 23rd of eleventh month, 1748.

[.salutation]
Dear Uncle,

In the bowels of unfeigned love do I salute you,
sincerely desiring your growth and increase in that
which is most to be desired by the children of men.
I have thought of writing to you for some time past, but waited for better tidings,
having been of late in a poor state of health by a
violent cold which I got from lying in a damp bed.
I strove with it, and kept travelling for some days, still growing worse,
but was forced to submit, and was laid up for nearly a week.
Kind Providence directed my steps to the house of an eminent physician,
a rich and good Friend;
where they were all ready to do every thing in their power for me,
and he skilful and free to administer what was suitable to my weak condition;
so that my mind was quite easy and resigned to the Divine will,
and I could not accuse myself of being the cause of it.
At my parting from them I would have made him some gratuity for his care and kindness,
but he answered in the humility of his mind with tears in his eyes,
it was the desire of both him and his wife,
that they might be found worthy to be the servants of
the servants of the Lord,--in whose love we parted.

The night before last I thought myself the nearest to my final change,
that I ever was since I received life;
+++[+++occasioned by a large sulphureous fire in her bed-room:]
the family were much frightened, and eagerly would have sent eight miles for a physician;
but I positively forbade it, and told them I should soon be better one way or other.
And indeed I was by the infinite mercy of God entirely resigned,
and as willing to go as stay.
I looked upon death but as a happy release from all my probations, dangers and troubles;
I had no condemnation in myself, the accuser of the brethren being cast down,
and a lively hope given me, that through the mercies of Christ my Redeemer,
I should rest with Him in unembittered felicity forever and ever.
It was the secret language of my soul to Him,
who knows the intents and purposes of every heart,
that my life might not bear a later date,
except it was more fully to answer the end of my being.

Oh! may the eye of my mind be made more single,
and my heart thoroughly fixed on Him who alone deserves it; that by dying daily,
I may know Him to live,
and being thoroughly emptied and unbottomed of +++[+++having no reliance upon]
myself, let Him be all in me; that so in Him I may live, move and have my being,
who is the saving health of His people, life in death, and strength in weakness:
may this be the desire of all my well-wishing friends
for me in their entrance into the sanctuary.
Oh! how desirable is that pure fear, which brings to obedience,
and exempts from all other fear, even of death itself,
which is to the disobedient a king of terrors!

Many are the dangers and hardships we meet with
by very bad roads and cold stormy weather,
which I often think no worldly motive could move me to;
but as it is in the service of the best of masters,
His Divine arm is underneath to support under all,
giving the rich reward of solid peace and satisfaction,
which far excels all this world can give or take away!
I have never yet repented my coming into this nation, but do humbly thank Him,
who thought me worthy of such a call;
and if my lot in this world should prove too hard for my natural strength,
I shall have no cause to regret that my pilgrimage will be soon over,
seeing the danger I am placed in here in an enemy's country,
having a continual warfare to maintain against three potent adversaries, the flesh,
the world and satan.
And oh! how many seeming brave soldiers have cast off their spiritual armour,
deserted their Captain, and shamefully quitted the field of battle;
which makes me fear always, lest it should be my unhappy case!
So that if I can live long in a short time by living well,
it will be better than if I could live a thousand years twice told,
to worse than no purpose.

Having poured out my thoughts freely as into the bosom of my friend,
I shall strive to draw to a conclusion,
desiring you may give my dearest love to your daughter and the rest of the family,
with all my kind inquiring friends as if named,
and accept a part yourself my companion joining,
from your truly affectionate and much obliged friend and cousin,

[.signed-section-signature]
Mary Peisley.

--

From London she wrote to a friend after this manner:

[.embedded-content-document.letter]
--

[.letter-heading]
To +++__________+++

There are many hindering things to obstruct us in our journey,
enemies within and enemies without; with the general lukewarmness,
and indifference about religion,
that prevails among the professors of Christianity of all sects and denominations,
so far as I see.
Their example,
instead of inciting to zeal for the cause of God and the pursuit of virtue and piety,
their deadness, dryness, carnality and insensibility,
are in great danger of leavening into the same spirit.
I find occasion for a strict and constant watch,
with fervent prayer to the God of my life, for help,
strength and deliverance from the flesh, the world and satan, which war against my soul.
I bless His great and glorious name, in that the Lord still continues,
by the inshining of His Divine light, to keep me sensible of my weakness,
frailty and manifold infirmities,
and the need I have of looking steadily to my holy Head;
and of the help of my fellow members, in the mystical body.
I have often desired, when scarcely able to pray or breathe +++[+++in prayer]
for myself, that He might be pleased to hear,
and have regard to their good desires for my preservation;
and I think I have often witnessed the benefit of the help of their spirits.

I have been through the north, south, east and west of this nation,
at the meetings generally, great and small;
there now remain several of the midland counties,
which I believe will take me up most of this summer;
and then I hope to see my native land in peace, which will be matter of comfort to me.
A large share of suffering has fallen to my lot, in this land;
but none of those things move me, neither count I my life dear, in comparison,
that I may win Christ, the hope of glory.
I have rejoiced to be found worthy to suffer for His sake,
knowing it is such that shall reign with Him.
Surely of all perils by sea and land, there is none so hard to bear,
as that from false brethren, which I have not been exempt from: but through all,
I am preserved in peace of mind, and restored to a far better state of bodily health,
than I once expected; for which great blessings, with all other unmerited favours,
I humbly desire to be made and kept truly thankful.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To two Friends in the Ministry

Many things have occurred to hinder my writing to you sooner;
not that I have any thing material to communicate,
except what concerns my own particular, which I hope you are not altogether strangers to;
if I may boldly lay claim to a part in the mystical body, whereof Christ is the head;
members of which, I fully believe you are,
and doubtless have had a feeling in spirit for a weak member suffering,
though far remote in body, yet present in Him who is omnipresent.
For I may truly say, of late, it has been a time of deep trial to my poor soul,
its Beloved having withdrawn as behind the curtain; and not only so,
but allowed the accuser of the brethren, to cast some of his most fiery darts at me,
and roar upon me like a lion;
yet was the Lord's good Spirit lifted up as a standard in the most needful time.
I humbly hope, it was for the refining of my faith, and fitting for further service;
because we can never so effectually or certainly speak of the wiles of satan,
and God's deliverance from them, as when we have seen them in ourselves.
If I know my own heart, I am truly willing, to be emptied as from vessel to vessel;
that so I may have no lees or dregs to settle on.
I do not complain of the Lord's dealings with me,
but rejoice that I am counted worthy in some measure to suffer;
and desire I may be humbly thankful, that He is using means,
such as comport with His infinite wisdom,
for my preservation from the epidemical disorders,
which abound in the visible churches professing godliness.

I travelled a week in the county of Suffolk in silence, was at six appointed meetings,
and had not strength to open my mouth in any of them;
a path I am ready to think more will be called into,
if rightly subject to the Divine will;
for the Church in many places groans under a lifeless ministry.

[.signed-section-signature]
Mary Peisley

--

She wrote the following letter to a Friend in the ministry,
who had been instrumental in the Lord's hand to impart such help and counsel,
as had a tendency to awaken her, when in the sleep of carnal ease and forgetfulness:

[.embedded-content-document.letter]
--

[.letter-heading]
To J. T.

Such a jealousy as possessed the mind of the eminent apostle,
concerning the believers in his day, has laid hold of me concerning you; which was,
lest he that beguiled Eve, should beguile you, from the simplicity that is in the Truth.
As I was this day in my solitary retirement,
it was brought to my thoughts to write you a few lines, and I reasoned thus with myself:
What shall I, who am a poor weak child, say to one who was in Christ before me,
and instrumental in the great Hand, to beget me in the Truth?
I likewise remembered,
the apostle travailed in birth for his little children,--made mention
of them day and night in his prayers,--wrote them excellent epistles,
and especially to his son Timothy, who was engaged in the weighty work of the ministry.
What excellent fatherly instruction does he give him, but none from the son to the father.
Where is yours to me, in this the day of my great trial and exercise?
Ah! where is that which should come upon you daily, the care of the churches,
or at least the heritages of your God?
I wish no other care may have intruded itself in the room thereof,
which may have caused you to fall asleep, in this lukewarm, backsliding, degenerate age.

Be aroused, for the Lord Jesus Christ's sake,
your soul's and the churches'. Consider what you are doing with these excellent talents,
which the great Lord has committed to your trust.
If you should cease to use them to the honour of His name,
those who are as the stones of the street, will cry out against you; and I,
if I keep my place,
shall be a witness to the sufficiency of that gift which you have received.
Do not again become a slave to the world.
Consider the dignity of your high and holy calling,
which is no less than that of a king's son, to be an heir with God,
and co-heir with Christ.
Allow not a sensual worldly tincture, to pervert your taste from that fountain of life,
which your soul had once so; quick a relish for and thirsted after,
even as the hunted hart does after the water-brooks.
Bear with my freedom and jealousy, which proceeds from the universal love of God,
that wishes well to all.
I would not have you think I write from prejudice of mind;
you know there is no cause for that;--nor yet from information.
No, I never heard one word against you, since I left you.

I should be pleased to hear from you, how it fares with you;
for I long to hear of your prosperity in the Truth,
which would be a great comfort to my poor soul, that oft goes mourning,
as between the porch and the altar, for the desolation of spiritual Jerusalem.
Let us so run, as not uncertainly; so fight, not as beating the air;
but keep under the body of sin and death, as well as the mortal body,
bringing all into pure subjection, and obedience to the holy cross of Christ.

--

The following letter was to a relation:

[.embedded-content-document.letter]
--

[.letter-heading]
To +++________+++

The one thing needful is only worth our care and constant pursuit;
and surely there are many impediments and hindrances in this dangerous deluding world,
that are often ready to turn us out of that narrow path, which leads to life.
This has my soul experienced, by being drawn aside through unwatchfulness,
and the prevalence of temptations;
and I have found it hard work to return into the right path.
I have many times thought, a soul rightly influenced, and affected with the love of God,
is like the needle touched with the loadstone; that whichever way it be turned,
rests not, nor settles, till it comes to its true centre; that is,
while it retains the virtue of the loadstone.

Thus it is with the soul, that has been quickened and renewed by that efficacious power,
which has been extended to draw our souls from earth to heaven; for certain it is,
they have a natural tendency to sink into the earth, or earthly enjoyments.
But unless we renewedly witness the visitations
of that warming heart-melting love of God,
which keeps the soul alive to Him, and brings into that holy fellowship,
which is with the Father, and His Son Christ Jesus, by livingly feeling Him to be in us,
and we in Him, all religion is but dead form and empty show.
As the branch cannot bring forth fruit of itself, except it abide in the vine,
no more can we, except we abide in Him, and draw sap and nourishment from the pure root,
bring forth fruit acceptable in His sight;
who looks at the purity and sincerity of every heart and soul.
He sees nothing in us, pure, amiable or lovely,
but as His own work of grace is allowed to be carried on;
that so Christ may be made of God to us, wisdom, righteousness,
sanctification and redemption;
and to do all in our power to facilitate and help forward this great and glorious work,
is the important business of our lives.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Gough

[.signed-section-context-open]
Lancaster, Second month 9th, 1749.

[.salutation]
Dear Friend,

I received your acceptable letter some weeks since;
I likewise heard of your near trial, in losing your bosom friend and dear companion;
in which trouble I have sympathized with you,
and sincerely desired that this with all other of the
Lord's dispensations may be truly sanctified to you,
and tend to the bringing home and centring your mind on that which is immutable,
and which cannot be snatched from you, so long as you cleaves to Him,
and are united to Him in spirit.
May all these things be as seasonable warnings to us,
the few moments we have to stay here, to turn our eyes from this transitory world,
conducting ourselves, or rather being conducted by our Great Pilot,
as passengers seeking the haven or port of rest;
not entangling ourselves with the unnecessary incumbrances of this life,
by which many have been drawn to perdition and error,
and have pierced themselves with many sorrows.
But as our worthy elders, who pursued their lawful affairs with moderation,
acting from a principle of justice and honesty,
to keep a conscience void of offence towards God and man;
demonstrating abundantly by their converse and commerce amongst mankind,
that they sought not to advance themselves or families to wealth, honour,
and dignities in this world, but contrariwise, to promote their Master's kingdom,
having a single eye to His honour in all they took in hand,
whereby their bodies became full of Divine light,
and in that alone were all the snares of satan discovered,
and power given to escape them.
Ah! my dear friend, may this be our happy experience,
that as the Lord has seen fit in his infinite goodness and mercy,
to call us with a high and holy calling, we may walk in pure fear and watchfulness,
so worthy of our vocation, as that we may be made and kept sanctified chosen vessels,
fit for His heavenly use, and so become pillars in His house; that we may never go out,
demonstrating whose servants we are, and what life we are governed by,
even that which is hid with Christ in God,
which deadens and crucifies to this present world, and the life and delights of it,
and leads the soul to seek and obtain celestial joys, while in these tabernacles of clay,
knowing that we shall shortly put off these bodies, and the soul appear naked and bare,
having no advocate but Him who has been in us.
Let us therefore use our utmost endeavours to make Him our friend,
by yielding perfect obedience to His dictates and blessed manifestations,
diligently waiting to know what His will is concerning us,
that so it may be as our meat and drink to do His work,
which He is pleased to count us worthy of, and to call us to.

Often is my mind brought very low under the sight and sense of the few in this day,
who are made rightly willing to bow their necks to the yoke of Christ,
whereby they might be made nothing to, nor of themselves,
thoroughly emptied and unbottomed, that so Christ might be all in them.
It is indeed lamentable to behold many up and
down in the churches who are elders for age,
and should be grown to the measure of the stature of the fulness of Christ,
bright way-marks and leading orbs in the firmament of God's power; instead thereof,
the dragon by his tail has drawn them to the earth.
Wells they are without water; dry withered fruitless trees, twice dead,
plucked up by the roots, being rich in words and expressions of former experience,
but out of the power of Truth, which alone can give a savour of life unto life,
and death unto death, and a certain alarm unto the battle of the Lord.
It often falls to my lot to sit in silence, as a fool, under suffering,
and in deaths oft;
for I believe it is the will of our God to have his
people drawn from sounds to Him the living substance.
May it ever be my care and concern, to keep with the precious Seed,
whether in bondage or oppression, for it is only such can truly reign or rejoice with it;
knowing the Lord to be my emptiness and fulness, having no other fountain,
well-spring or treasure; for it is in this alone I can find solid peace,
lasting satisfaction and safety, even in being nothing but what He is pleased to make me.
And the longer I am exercised in the great work of the ministry,
the more weighty and mysterious I find it to be,--the less capable and +++[+++more]
unfit I find myself, that is of myself, to meddle,
or do any thing in it,--and the more need entirely to depend
on and wait for the coming and opening of the Word of life,
(in which the state of the churches is felt and spoken to) and
that is the very quintessence of a true ministry.
Often are the secret cries of my soul to the Lord that
he would cause true judgment to begin at the sanctuary,
at the head and at the heart, that so right soundness might be found therein:
then would the whole body be built up and edified in love.
And blessed forever be the holy name of our God!
I hope and believe there is yet a remnant preserved on the face of the earth,
who prefer Jerusalem before their chiefest joy,
and the peace and welfare of Zion more than their fives: but oh! they are too few.

Friends in a general way are very kind and tender to us,
bearing with our infirmities and weaknesses of mind, which are many,
though by Divine mercy I am much better than when I left home.
May I be found worthy of being brought by the Eternal Spirit
into the remembrance of the living body in my native land,
when they are made glad in His holy house of prayer;
for surely I have need of every help,
considering the great engagement I am under in these perilous backsliding days.

[.signed-section-signature]
Mary Peisley

--

The following letter was written to a Friend in the ministry.

[.embedded-content-document.letter]
--

[.letter-heading]
To +++________+++

Since we parted, you have been so much in my thoughts,
with strong desires for your preservation and growth in the ever-blessed Truth,
that I could not avoid saluting you by a few lines,
in that love which seeks the peace and welfare of Zion,
with the enlargement of her borders; which a remnant are at times deeply concerned for.
And ah! says my soul, may no other concern whatsoever,
erase the remembrance of it from our minds,
so as to hinder us from preferring it before our chiefest joy.

This is what will make for our peace here, and eternal salvation hereafter;
which it is our business and interest to pursue,
with the utmost vigilance our frail nature is capable of,
seeing our adversary goes about like a roaring lion, seeking whom he may devour;
and not only so, but as a subtle serpent, working in a mystery of darkness,
by which he has drawn down to the earth many bright stars,
causing them to contend for the glory, honour and friendship of this wicked world,
instead of the precious faith delivered to the saints; which powerfully works by love,
to the purifying of the soul, and making them pure and holy,
as He that has called them is holy.
Oh! may my soul fear always, lest I, or any of my dear brethren and sisters in the Truth,
should fall short of an admittance in the great and notable day that draws near quickly.

When I consider the very few bright shining examples that this age affords,
who have disinterestedly devoted themselves to the service of Truth,
and been kept unspotted of the world,
having on the white linen which is the righteousness of saints; my fears are augmented,
and my cries to the God of my life increased, not only for my own preservation,
but that of his heritage in general.
In a peculiar manner,
am I concerned for those whom he has called to the weighty work of the ministry;
that the eyes of our souls may be kept so single to the honour of God,
as that we may minister suitably, from the Divine Spirit,
to the states and conditions of the people, without partiality, or respect to persons;
for in this case, (as says the apostle) if we have respect for persons, we commit sin.
In order to avoid this heinous, dangerous crime,
we had need to take notice of the wise caution frequently mentioned
in the writings of our worthy elders and faithful ministers,
in the morning of this latter day; not to be taken by the affectionate part with any,
lest it should prevent seeing rightly the situation of the lowly seed of immortal life,
and hinder ministering suitably to it,
but minister life and strength to that which should be slain, famished,
and brought to the death of the cross!
O! may we fulfil our ministry, so as to be pure from the blood of all men,
in the tremendous day of account, studying to show ourselves approved unto God,
as labourers that need not be ashamed, rightly dividing the word of Truth.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Beale

[.signed-section-context-open]
Lancaster, 11th of second month, 1749.

[.salutation]
Dear Cousin.

I heard of the death of your worthy mother,
who I doubt not is removed from a place of affliction, pain and probation,
to the full fruition of unembittered felicity, endless joy and peace; whose loss to you,
my relations, to whom she stood in the place of a parent, I am sensible is great,
and perhaps more than you can at present conceive or imagine.
For I know youth are apt to think the greatest happiness in this life,
consists in having liberty to gratify their will without control,
which till they know to be governed by the will of God,
is one of the greatest trials and dangers that can befall them.
I well know by experience the disadvantage it is to
lack the care and instruction of a good mother,
which makes me the more to pity your case.
Had not Infinite Goodness arrested me in my headlong race,
it would have brought me to the gates of destruction and the chambers of death,
terminated in my utter ruin both of soul and body,
by bringing me to infamy here and eternal misery hereafter;--
and all this by gratifying a vain and carnal mind,
which hurried me so precipitately into youthful pleasures,
that I had not time to see and consider the danger I was in.

And now my dear cousin, I have to reflect on the difficult station you are placed in,
and the great duties that will necessarily fall to your charge in your tender age,
as that of a mother to your younger sisters and brothers,
a help and companion to your father, and a stay to his family:
all which I have sincerely desired you might be
rightly enabled honourably to acquit yourself in;
and that must be by timely and carefully applying to
the Fountain and original Source of all true wisdom;
entirely disclaiming and renouncing all strength and sufficiency of your own without Him,
who is power and perfection itself.

Let it be your care to gain the love and affection of the younger children and family;
and yet keep an awe and an authority over them, as an elder and superior;
and the way to hold that is,
not to allow word or action of yours to be but what you could
with pleasure have brought to light and discovered to mankind:
otherwise instead of being their governess,
you will become their servant and a slave to the fear of their discoveries of you.
You can hardly think how much your prudent conduct and good example will
contribute to the good and well-being of your brothers and sisters,
both here and hereafter, and redound to your credit and satisfaction;
and if they should not tread in your footsteps, when guided in the path of virtue,
then will you be clear in the sight of God and man.
And above all things be sure carefully to avoid and shun vain,
profane and loose company of every kind, and all converse with them,
and unprofitable books and writings;--both insensibly tincture and poison the mind,
gradually leavening it into their own wicked nature,
dropping malignant dews on virtuous tender plants.
But let your communications be with the most solid religious Friends;
and when such cannot be had, choose rather to be alone and conversant with yourself,
attending on the reproofs of instruction and the manifestations of Divine light,
which is the very way to eternal life; acquainting yourself with the Holy Scriptures,
and the writings of learned and pious persons.
Thus will you gain to yourself a valuable treasure of wisdom and knowledge,
which possesses a mind rightly cultivated,
and be made fit for converse with God your Creator and his saints on earth;
having your body a sanctified receptacle for His blessed Spirit to make His abode in;
which is the height of perfection and excellency that our nature is capable of.
Let moderation and the limits of Truth bound you in all things, eating, drinking,
sleeping and apparel; being adorned with a meek and quiet spirit,
which is the ornament of our sex.
Yet does not this lead to a dull inactivity of mind,--no,
but rather awakens the soul to a sight and sense of duty;
and to exert ourselves in the places Providence has placed us,
that so we may not become burdens and drones in the creation.

These things, dear Sally, have I written in much love,
and hope you will excuse my freedom,
and accept them in the same from your affectionate cousin,

[.signed-section-signature]
Mary Peisley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. and T. Ecroyd.

[.signed-section-context-open]
Exeter, 26th of Sixth month, 1749.

[.salutation]
My Dear Friends,

I have been with my dear companion Mary Weston,
since the yearly meeting, through four of the southern counties;
a fine well-cultivated country, whose fields seem to lack no improvement,
being richly adorned with plentiful crops.
These, with beautifully enamelled and fragrant pastures,
with dumb eloquence abundantly praise and magnify the great Creator,
setting forth to every intelligent mind the magnificence of His power, wisdom, goodness,
bounty, and long-suffering to a race of degenerate unworthy mortals,
whose tongues are filled with cursing and profaneness,
instead of thanksgiving and praise for the unmerited favours
of Him who makes His sun to rise on the evil and on the good,
and sends rain on the just and on the unjust!

So far as I am capable of discerning,
religion is at a very low ebb in this part of the world,
amongst all ranks and societies of people.
Perhaps you will say I lack charity, or upbraid me as Joseph did his brethren,
of coming to spy the nakedness of the land.
I tell you no, but to buy food for the sore famine of my soul, by obedience,
which could I have had at home I would not have come here.
Though I thus freely write my thoughts as they occur,
I have no doubt but I am known by you, as well as Joseph's brethren were by him,
though to many where I come I am unknown, and remain so.

I have far passed the limits of my letter, but feeling my heart enlarged in that love,
which neither length of time nor distance of place can extinguish or impair,
hope you will excuse the freedom, and accept of my salutation in the unchangeable Truth,
in which I greet you with love unfeigned, also to your father, mother, and family,
with any other inquiring friends, as if named, from your truly affectionate friend.

[.signed-section-signature]
Mary Peisley

--

A letter written to two Friends, to whom she was nearly united in spirit, runs thus:

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_____+++ and +++______+++

I received your acceptable letter at London, and would have answered it before now,
but for lack of leisure, and sometimes a fit frame of mind,
being many times deeply bowed and dipped into suffering, with and for my fellow members,
and the Seed of God, which lies loaded and oppressed in the minds of very many,
even the professors of the blessed Truth, as a cart under sheaves.
This makes the true ministers of Christ go heavily mourning on their way,
often strewing their tears in solitary places,
for the slain of the daughter of this people; yes,
for His sake we are killed all the day long, and accounted as sheep for the slaughter.
Surely, of all perils we meet with by sea and land,
there are none so dangerous or hard to bear, as by false brethren:
such are they who have lost the spirit and power of godliness, but retain the form;
being clothed with a Pharisaical righteousness, they, as our Saviour said,
sit in Moses' seat.
What they bid, we may do; but their example is to be shunned:
instead of coming up in their footsteps, we may justly cry,
my soul come not into their secret; unto their assembly mine honour, be not you united;
for their steps tend to the chambers of death,
and their ways to the sates of destruction.
O! the great loss we that are young have, for lack of steady elders to go before us,
who might take us by the hand with this amiable language, "`follow us,
as we follow Christ.`"
And as this is the lot of our day, we must strive to keep to our great Pilot,
who is the alone safe conductor of His followers, through all the storms, difficulties,
and dangers, that attend this pilgrimage and vale of tears.
Though He may sometimes allow us to walk by faith and not by sight,
yet as our eye is steadily looking unto Him,
He will be found near at hand to help and direct;
whose holy life (while in that prepared body,) remains
to be an unerring pattern--He in whom there was no sin,
neither was guile found in His mouth,
who was a man of sorrows and acquainted with grief Alas!
how hard a lesson is this to our corrupt nature,
poor, frail, weak creatures!
Ah! what need we have of boundless mercy,
and the mediation of a tender compassionate Saviour, a holy High-priest,
that was tempted in all points as we are;
and who well knows how to succour all the tempted, whose care is cast upon Him,
the government of whose hearts is upon His shoulders,
those who have surrendered their wills to his.
These, and only these,
are made truly free from the thraldom of sin and death--know an overcoming of themselves,
the world, and the devil,--the only conquest worth our labour and constant pursuit.
May we ever keep so near that holy, animating seraph love,
as that we may witness it to fill us with a generous
indifference to earthly and transitory objects;
that so we may in reality, count all things here as loss and dross,
in comparison of that excellent treasure which we have in our earthen vessels;
the efficacy of which has at times given a disrelish to
everything that would impede its pure arising in the soul.
It is the constant care and work of our adversary to strive to blind the eye of the mind,
which can discern the transcendent excellency of the eternal Truth.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Father

[.signed-section-context-open]
Bury in Suffolk, 3rd of First month, 1750.

[.salutation]
Dear and Honoured Father,

I rejoice to hear of the welfare of
my dear brothers and sisters in the best things,
and sincerely desire that the dew of heaven may rest long on
all your branches--the blessing of the everlasting hills;
that so you may be a sweet savour of righteousness to
Him who has called with a high and holy calling,
to be heirs of His kingdom, which is far beyond all the kingdoms of this world.
O! may you and I press after it through all the
crowds of opposition that may stand in our way,
so as to touch the hem of His garment from whom alone healing virtue comes.

I have, by Divine mercy, been favoured this winter with an uninterrupted state of health;
for which favour, with many more I am partaker of,
I desire to be made and kept truly thankful.
I have not had the least touch of my cough,
which has been so afflicting for many winters past:
it has been the most favourable season for travelling, the time of year considered,
that ever I knew.
I am just got through this county; I think of going next into Essex,
and from there to London, in order for a visit to the city,
which I have not yet performed.
A young woman has accompanied me through three or four counties;
she is to leave in a few days, and my dear Mary Weston is to meet me,
and take me home with her.
You desires to know how I am horsed, which is as well as I could desire, a fine-going,
sure-footed, free, pretty creature as ever I rode; it has no fault that I know of,
except full much spirit, which is nothing to me now I am used to her.

It has been for some days past a very poor low time as to my mind;
I have now got to a worthy family, with whom my spirit has this evening,
in a little family meeting, been much refreshed and comforted.
O! how good is bread to the hungry, and the water of life to the poor thirsty soul;
and how pleasant is that fellowship which is with the Father,
and His Son Christ Jesus;--surely it is beyond and above all
the nearness of affinity or consanguinity outwardly;
but where they both unite, they are the two-fold cords not easily broken.
May we, my dear father, know an increase of this pure unchangeable love,
and grow in it as we grow in years.
From your dutiful and truly affectionate daughter,

[.signed-section-signature]
Mary Peisley

--

She mentions, that at the city of Cambridge, she had a meeting with a few professors,
in number about five;
where she was greatly favoured in her mind with the living presence of God;
in whose light, she says,
"`I saw and was made to believe that there would be a people raised up in that place,
who should stand for the honour of His name, and be valiant for Truth on the earth.
This I was led to declare to the few present,
though at this time in a place noted for contrary fruits.
At Burford had a large and precious evening meeting,
though in the early part it was a very suffering time, there being several priests,
justices of the peace, so called, and rude people,
in whom the prince of the air had dominion; but the Lord,
whose power is above every power, manifested His own Arm,
and made it bare for the help of His depending children, who have none in heaven but Him,
nor in the whole earth in comparison of Him.
His testimony was set over the heads of transgressors,
and evil spirits were made subject to His power:
everlasting praises be given to His excellent name!

"`At another place where I had a meeting,
the professors of Truth had heard of my being silent at several meetings,
and were afraid of the cross and reproach of men, so took me a back way to the meeting,
for fear (as I apprehended) their neighbours who were not of our Society should see us,
and come there; yet Providence so ordered it,
that a large number came to the afternoon meeting, to whom Truth was declared,
in the wisdom and demonstration of the Spirit of God;
after which I had to speak closely to the professors.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To her Father

[.signed-section-context-open]
Wapping, 28th of Second month, 1750.

[.salutation]
Dear and Honoured Father,

I have been in this city near a month,
which has proved a time of deep travail,
having been much shut up and under suffering of spirit;
but I think it a blessing that my lot is cast with such tender
sympathizing friends as my dear M. W. +++[+++Mary Weston]
and husband; but I am soon likely to lose her out of this nation,
she being prepared for an American journey, only waiting for the ship's sailing.
I am glad for her and the cause' sake,
that the Lord has so far prevailed by His love as to make her
willing to leave all these near and dear enjoyments,
and her good husband to give her up cheerfully.
Her company has been a great comfort and service to me,--the Lord
reward her for all acts of kindness and love to poor unworthy me.

[.signed-section-signature]
Mary Peisley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Peter Peisley

[.signed-section-context-open]
High Wycombe, 30th of Third month, 1750.

[.salutation]
My Dear Brother,

Live you in the pure fear of your God, which is a fountain of life,
that preserves from the many snares of death,
which the wicked enemy is laying for the feet of the youth.
O! what need have we at all times to keep near the Divine light in ourselves;
and to watch in the same against every appearance of evil, and above all,
our own heart's lusts;
seeing the devil our adversary goes about as a roaring lion seeking whom he may devour.

Dear brother, I cannot but warn you in the love of God,
to have a strict guard to your words, as well as actions;
and at all times to speak the truth from your heart, whether it be for or against you:
neither equivocate to excuse yourself in a fault, for that is next to, or one degree of,
lying; but rather suffer blame, if you have omitted any duty,
than provoke your Father and Master in heaven;
for if you anger Him and make Him your enemy, you will never prosper in the Truth.
And not only lying, but vain talking and foolish jesting grieve the Holy Spirit;
therefore let no corrupt communication proceed out of your mouth,
but such as is good for the use of edifying.
Remember that for every idle word we speak we
must give an account in the day of judgment,
and all liars are to have their part in the lake that burns with fire and brimstone,
except they know a true and sincere repentance.

But dear brother, I hope better things of you, and things that accompany salvation;
nor are these hinted at as charges,
but as cautions from one who has seen the workings of Satan various ways,
and who sincerely desires your welfare and preservation every way,
and therefore I must again in pure love entreat you,
to watch against all vain and unprofitable thoughts, as well as words,
and especially in religious meetings appointed for the solemn worship of Almighty God.
If you allow the enemy to carry your mind from the pure gift in yourself,
you will sustain great loss, and bring death, weakness, dryness,
and barrenness over your soul:--Satan working in a mystery of darkness,
filling the mind with vain thoughts, and lofty imaginations of self,
which must be crucified and slain,
before there can be a right resurrection of the soul in the Life of God,
And though you mayst frequently find it very hard to
have your mind composed and staid on the Truth,
when coming out of a hurry or multiplicity of business, yet be not weary of striving,
watching, and praying, according to the ability you have received;
watching for the manifestations of the Divine light;
that so you mayst see your state and condition,
and from that sight and sense know how and what to pray for as you ought:
for we know not how to pray acceptably, but as the spirit helps our infirmities.

I understand your master and mistress are kind to you,
the former entrusting you with a share of his business,
in which I hope you will acquit yourself with the same
strict care and industry as though it was your own,
yes, and more so;
for we may make much more free in omitting or neglecting our own affairs,
than when entrusted for others: and I have to say for your encouragement,
it is my belief if you keeps near to the Lord and are faithful to Him,
He will do more for you than you can now think.
This is the testimony of one, whom He has deeply tried in the furnace of affliction,
yet who has found Him a God near at hand in every time of trouble, and besetment,
and exercise: to whose protecting care I commit you with myself, body, soul, and spirit,
and in His love I salute you, and remain your affectionate sister,

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To her Father

[.salutation]
My dear and honoured Father,

In a fresh and renewed sense of that love,
which is far surpassing natural affection, but joined with the latter,
do I at this time tenderly salute you, my mother, and the family;
greatly desiring your growth and preservation in that
which as much transcends all temporal enjoyments,
as light does darkness.
May you be found in close union with the Eternal Spirit;
wherein you may read and feel me in the life,
and see my situation and standing in the ever-blessed Truth,
and make intercession for me according to the will of God.
It is here that we come rightly to discern one another,
not by the sight of the natural eye, and report only;
but the soul finds out the excellency of the soul, that is,
the beauty which Truth has invested it with, by its own light; for, indeed,
we have neither beauty, nor excellency, but what we derive from Him,
who is the inexhaustible fountain and treasury of all the saints' jewels.
If we take them to deck self with, when He is not pleased to have them exhibited,
it is robbery;--a sin (I bless His name) He has hitherto preserved me from.
But He has made me willing to pass along in my journey and pilgrimage as a fool, naked,
bare, destitute of help, excepting as I received it from Him,
who is the Helper of his people, to the astonishment of professors and profane.
This has exposed me both to their censure and ridicule,
with grievous mockings and scoffings, hard to be borne by flesh and blood.
But He, to whom my eye has been, and whose honour I have sought and not my own,
did not leave or forsake me, under my many and great trials;
but the right arm of His power has been underneath in all my exercises and probations:
so that my soul yet lives in the existence which is invisible and eternal,
through all insults of the enemy within and without:--to His excellent name,
who is everlastingly worthy, be all praise!

O! how is my mind filled with admiration,
when I consider the multitude of His mercies and admirable preservations,
in imminent dangers, both inward and outward, by sea and land,
as well as His mercies to you my dear parents, brethren, and sisters,
with others of my dear relations, who are near to my life,
and who are brought to my remembrance at this time as at many others,
with great sweetness;
and for whom I bow the knee of my mind in reverence at
this time before their God and my God,
their Father and mine.
To these my love flows freely in the blessed fellowship of the glorious gospel;
to any of these dear children, co-heirs with Christ, who inquire for me,
in that love that is immutable, you mayst communicate this account of my welfare,
as freedom and opportunity permit;
knowing these will rejoice to hear of my preservation in the Truth, as I do of theirs:
and I trust by the permission and ordering of Providence,
shortly to see some of their faces, and enjoy a sweet communion in that love,
which first united our souls and cemented our spirits,
making us witnesses of that incomparable fellowship which is with the Father and His Son.

I have nigh accomplished my great journey, and to my inexpressible consolation,
possess that peace which surpasses the understanding of man;
finding myself quite clear of the several parts of this nation that I have visited,
which I look upon as an inestimable favour from Him to whom I am abundantly indebted.
I have left but a few meetings and two small counties,
which I hope to accomplish in about a month; but if it should be longer,
I would not have you uneasy, as I am in the hands of a powerful and gracious God;
to whose protection I commit myself, you and yours.

I had your letter at Leicester, three weeks since, which I was glad of,
and pleased with your seasonably reminding me of the many
obligations your family and I lie under to Almighty God;
which cannot be too frequently remembered, nor gratefully acknowledged.
O! how does it humble my mind, when I reflect that many accounted as valiants in Israel,
who had enlisted under Christ's banner,
but who for lack of keeping in the valley of humility,
and near the Captain of their salvation,
have suffered themselves to be wounded by their adversary,
and have fallen as on the right hand and on the left, while I, a poor weak worm,
who have no strength nor might of my own,
am still preserved in the fear and love of my God,
though dangers surround me on every side!

I am favoured with the agreeable company of a young woman from Worcester,
who has been with me about six weeks; though she has not a gift in the ministry,
yet she is one of those who travail in spirit, and who sympathize with the ministers,
a plain, humble, meek-spirited woman, though in the possession of a plentiful portion,
and that at her own disposal, being fatherless and motherless;
three sisters of them live together in good repute;
yet she willingly left her comfortable habitation,
to partake of harder fare and difficulties with me,
doing what was in her power to make her company serviceable and agreeable to me.
I wish there were many such examples in this and our nation.

I shall conclude in that love wherewith I began, to self, mother, sisters, brothers,
friends, and relations, as opportunity serves;
which please to accept from your dutiful and affectionate daughter,

[.signed-section-signature]
Mary Peisley.

--

"`In the latter part of this journey, I was seized with a violent intermitting fever,
which illness detained me several weeks,
and caused me to travel in great bodily weakness;
yet the Lord was graciously pleased at times,
to strengthen me for the service he had called me to,
beyond my own and others' expectation.
I waited near a month for a passage to my own country, which seemed tedious to me,
and some of the time at a public house at Parkgate, destitute of friends or acquaintance,
but dared not repine at the will of Providence.
In this journey I rode about five thousand miles,
and attended five hundred and twenty-five meetings.

I landed at Dublin the ninth month, 1750,
having been about two years and nine months absent.
Had the company of my esteemed friend, Samuel Fothergill.
We had a rough, but swift passage, and were in danger of driving upon the Welch coast,
but the Lord was our preserver.
My friends rejoiced to see me, as I did them;
some were concerned at the state of my visibly impaired health.

In this city I felt great weakness of body and mind, being stripped, emptied and tried,
as before the great Judge; by whom I was willing to be examined,
and to bring my deeds to His Divine light,
where my own weakness and manifold infirmities might be more fully manifested;
it was several days before I was able to go out to meetings.
Though my life was despaired of by several, I mended in my health faster than I expected,
when I repaired to my father's cottage,
where all the needs of nature were fully supplied,
excepting that which would gratify the lust of the eye,
the lust of the flesh and pride of life.
Some were against my coming, fearing the journey would be too much for me,
and the accommodation not suitable to my weak condition; but I bless the name of my God,
who never permitted me to lack any good thing, since my first knowledge of Him.
I had great peace in coming to my aged father, who much desired my company.
Invitations I had, to stations of great affluence, but I denied them;
and found the Lord my God deserts not the poor and mean of this world,
but visits them in their lonely situations and humble retirements before Him:
this I am a witness of, for He was often with my spirit in this time of weakness,
speaking peace and comfort to my soul that could not live without Him.
One day in particular, as I rode to meeting, being much better in health.
His living word ran sweetly through my mind,
thus,--"`For this purpose have I raised you up,
to show forth in you my power of preservation
and mercy,`"--which greatly rejoiced my soul,
and caused me to praise His excellent name, who is everlastingly worthy,
for all His mercies.`"

She kept pretty much at home during her weak state of health, and about this time,
wrote to a Friend as follows:--

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_________+++

By the mercy of Providence, I am now much recovered.
Ah! says my soul,
may I answer the end for which I am continued longer among dreams and shadows,
mingled with deceit.
What soul that rightly knew its true centre,
would desire to continue here longer than till it had
performed the will of Him who sent it into life.
This is a state of infirmity and dependency, environed by the most subtle, potent,
unwearied enemies; which loudly calls for the greatest vigilance, fear,
humility and watchfulness that our nature is capable of.
Let us therefore sink down in our minds to the lowly humble Seed of everlasting renown,
where the visions of life and light are seen,
and the voice of the great Oracle heard distinct from every other sound,
in the silence of all flesh, freed from the noise of archers;
where none can make us afraid.

[.signed-section-signature]
Mary Peisley

--

In another letter she says:

[.embedded-content-document.letter]
--

I often wonder,
why the Lord and his people should show so much regard to a poor and unworthy creature,
who am the least and last of his family, if fit to be esteemed of that happy number.
My soul sinks low under the weight of obligations to Him, to whom I can make no returns,
but of His own begetting, who measures not His mercies by our merit,
for then would they be a scanty portion;
but they are proportioned to His matchless love and kindness.

--
