== Chapter III

The summer following she accompanied Catharine Payton,
who came to this nation on a religious visit,
finding a draft to join her to Munster and Ulster.
She set forward on this journey in the Fifth month, 1751,
and they joined as companions at Waterford.
They had many meetings amongst those of other societies.

They visited the towns-people of Sligo in Connaught, and felt much satisfaction;
she thought they were well worth visiting,
and said there seemed much more openness to declare the
Truth amongst those of other societies,
than amongst them that go under our name.
After this journey, she stayed most of the winter with her father.

[.embedded-content-document.letter]
--

[.letter-heading]
To Robert Bell

Your epistle of the 19th instant, is now before me;
and though I am not one of the dignified people, a scholar,
or a woman of strong natural parts, yet find freedom to send you a few lines,
divested of all the embellishments, which might proceed from the above endowments:
having nothing to recommend me except a considerable stock of simplicity and sincerity,
I am under no temptation to begin a correspondence to show my wit or learning.
In the first place, I may let you know I am in health of body, except a cold,
and fear this part prospers better than my soul prospers;
as the former breathes in good clear air, has bread to the full,
and I know of no enemies that seek its life;
the latter is in an enemy`'s country surrounded with treble danger,
in a land of infection,
where fogs of sense and damps of spleen are at times
ready to suffocate and stop the breath of life;
and had not the sovereign medicine, the balm of life, been applied,
it must inevitably have perished long before now.

When you mentions the honour done to yourself in conducting your friends,
I would gladly hope you means the honour your soul
received in feeling the love of God amongst His saints;
for surely all other is from beneath,
and therefore ought to be condemned by every noble-hearted Christian,
who seeks and aspires after that which is from above only.
As to what you observes concerning spoiling the feast,
it brought me to recollect an observation I the other day made,
on beholding a considerable number of bees resort to a rosemary bush in full bloom:
I stood with attention to see and hear these little busy active creatures,
and at length singled out one that I might more
particularly observe its manner of proceeding,
in order to accomplish its design;
which I apprehend to be a provision for the approaching winter,
though at a considerable distance, it being now the middle or early part of the season;
yet their diligence seemed to be as though it
was the last day:--but to proceed with my remark.
The one I fixed my eye upon swiftly fled from flower to flower,
perhaps to the number of ten, only just stayed long enough on each flower,
to find there was not the sweets it wanted; and then quickly fled to another,
not spending its time idly, buzzing about the empty flowers, nor did it sting or stain,
at least not obvious to my naked eye; indeed I thought,
could it have left some private mark easy to be discovered to its fellow-labourers,
without defacing or hurting the empty flowers,
it might save many the trouble of lighting thereon: but this was not to be the case,
they were all on an equal footing, each to try for themselves.
Nor were they discouraged by their fruitless endeavours, but persisted in close labour,
until they found what they wanted: life seemed precious to them,
for the preservation of which they bent all their endeavours.
If you can draw encouragement or instruction from these broken hints, my end is answered.
I have sometimes seen these above-mentioned creatures rest on a loathsome dirty sink,
and have been ready to think it was not bare curiosity,
or to stand as idle spectators on the meaner insects that resorted there; no,
I believe they extracted some of their materials for completing their work.
This I think I know, the laborious faithful Christian, draws instruction,
warning and caution from the worst examples.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth Carleton

[.signed-section-context-open]
Paddock,^
footnote:[Paddock was a farm in the occupation of Mary Peisley`'s father;
it was situated near Mountrath.]
11th of Tenth month, 1751.

My Dear Friend,--Be assured that it is not because I have forgotten you,
that you have not heard from me sooner,--no, you have been much in my thoughts,
and that with considerable love and sweetness;
but various cross occurrences have happened to prevent me telling you so till now,
among the latter of which was, a bad sprain in my right thumb,
which rendered my writing impracticable.
I received it by a violent fall from my mare the fifth-day before I got home.
This, with the enclosed, is the first I have been able to write,
which was not performed without some pain and difficulty;
but I have the utmost cause to be truly and humbly thankful,
that some of my limbs were not broken, or my life suddenly taken away.
O! how wonderfully kind has God`'s protecting Providence been,
to one of the most unworthy of all His servants.

Dear Elizabeth, I have often considered your lonely situation,
and compared it with my own; but mine is abundantly more so than yours,
not having one of my own sex in all this quarter,
that I can make a friend or companion of.
But I am greatly satisfied, and contented with the will of a wise Providence,
in this and all other of His dispensations;
as it gives me a better opportunity of communion with myself and Him,
who is the chiefest among ten thousands.
This is indeed an employ best becoming the nature of my being,
and the highest use of my intellectual faculties;
and if I could not repose myself in the quietude of my own mind,
and serenity of my conscience, with the refined pleasures arising therefrom,
in vain would I rove in these regions of woe, to seek happiness.
But I bless the name of my God, who makes the lonely cottage more pleasing to me,
than a palace can be to those dark souls, who live as without Him in the world.
Of a truth, the heaven of heavens cannot contain the Beloved of our souls.
He delights to be in the habitable parts of the earth amongst the children of men,
even with the empty, the poor in spirit, the contrite ones,
the temples of whose souls He has caused to be emptied,
swept and garnished with His own righteousness: and as He has made them clean.
He loves to visit them, and sup with them, and they with Him.
O! unparalleled kindness, matchless love,
and astonishing condescension of our heavenly Father, and noble Benefactor,
to the despised children of His kingdom, whom He has chosen out of the rudiments,
customs, and fashions of this world.
"`Fear not,
little flock,`" said He,--"`it is your heavenly
Father`'s good pleasure to give you the kingdom.`"

I had not the least thought of writing after this manner, when I began,
but have just let my pen run as matter opened in my mind,
and thus enlarged my letter beyond my expectation, as love has enlarged my heart,
without premeditation, form, or connection:
if it conveys to you the least comfort or satisfaction, the end is answered;
for I have been ready to think you needs consolation, and say unto you,
in the unalterable love of the gospel,--Trust in that God,
whose truth and righteousness never fail: He will arise in his own time,
and expel darkness, and dissipate sorrow!

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Young Man, then under the Baptizing power of Truth.

There is one caution that has dwelt for some time on my
spirit to give you in pure love and good-will,
that is, that you may be particularly nice in the choice of your friends,
now in your setting out in a new and spiritual life, which is a point of great wisdom.
Have special care of being too readily taken with strangers,
and of giving your sentiments in word or writing of persons or things not well-known.
This you will find, when duly considered, to be a hint of singular service.
Wait for the freedom and direction of Truth,
before you enters into converse or familiarity with any,
though it may be on religious subjects; for there are many more talkers of the Truth,
than walkers in it.
This you will find, as I have done,
to tend greatly to the health and well-being of your precious soul;
for there is a set of mortals,
whose very breath diffuses poison and infection to the mind;
their throats are as an open sepulchre, the poison of asps is under their tongues,
they flatter with their lips: I might enlarge on this subject,
but a watch word is enough.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Paddock, 30th of First month, 1752.

[.salutation]
Respected Cousin,

Yours of the 30th is now before me,
which I have read and considered in the best manner I am capable of,
with desire that I may draw from it whatever instruction it can possibly afford me.
I have renewed occasion to see and admire the kindness, love,
and benevolence of my dearest tender Father and best of friends,
who has hitherto supported my mind under a multiplicity of uncommon exercises and trials,
both inward and outward,
for a series of time to the alone honour of His most excellent name.
I write not this boastingly; no, my spirit reverently bows towards its true centre,
in a deep sense of my own unworthiness of the least of all the
Lord`'s mercies and truth that He has showed to me;
and, blessed forever be His power, is still manifesting,
and I trust will continue so to do during the
short time allotted for my continuance here.
He it was, the Beloved of my soul,
whose I am and serve with my spirit in purity of conscience,
that fortified my mind for the reception of your letter;
which came to my hand at the close of our week-day meeting,
which had been to me a time of favour;
wherein my will was so far annihilated and spirit subjected,
as to feel no desire of being anything, either in the Church or the world,
but what might contribute most to His honour, not my own,
who had sent me into life for a purpose of His glory.
Oh! says my poor soul with the utmost sincerity, may the glorious end be answered,
then come life or death, prosperity or adversity,
shall I not bid welcome to all the dispensations that are sent to effect it; yes, surely,
and be willing to be anything or nothing, do or suffer for His name`'s sake,
who has deeply suffered for me.

I shall now endeavour to obviate your false surmises respecting me,
with no other view or intent,
but to prevent the evil tendency your entertaining them may have in
destroying that union and fellowship which ever did and ever will
subsist between the true members of the one mystical body,
so long as they keep their places and act under the direction of the Holy Head.
But really when they quit this beautiful order and harmony,
they are subject to hurt and trouble one another,
which I have found by sorrowful experience.
Ah! may such crooked, decrepit, weak, members,
who have made themselves so by acting in their own wills,
be timely reinstated and brought into union with the body and subjection to the Head!
As to the path which my feet were turned into,
out of the broad way (in which you were made an instrument in the hand of God,
and I hope I shall remember your agency with gratitude so long as you keeps in the
Spirit in which you began--may you nor I never seek to be made perfect by the flesh)
--I bless the name of my God I find by experimental knowledge that I am still in
the same strait and narrow way which leads to life eternal,
nor are my trials and self-nothingness diminished but augmented,
though custom has rendered them more tolerable to bear.
But I hope you would not have me always remain in a
state of infancy and weakness as to religion;
no, I desire to grow from stature to stature,
and from one degree of strength and faith to another,
till I come to the measure of the stature of the fulness of Christ:
in malice I would always be a child, but not in knowledge.
Yet I hope I have kept to the simplicity in innocency, honesty and plainness of speech,
not boasting myself in another man`'s line;
and though the terms in which I convey my sentiments may differ from yours or another`'s,
yet it is to me free, easy, and natural,
such as I am accustomed to in my common converse,--not laboured, strained,
borrowed or picked up as you term it,--and I think intelligible even to weak minds,
and those who with myself may lack the privilege of a liberal education;
for indeed I lay claim to no embellishments, neither natural nor acquired,
but such as I have been assisted to bring from the school of Christ.

True it is I have been careful in the discharge of my ministerial function,
to convey the Word as much as possible free from the workings of my own spirit,
or mixture of the creature,
seeing clearly that in these things Satan would
transform himself as into an angel of light:
setting sound for substance, and passion for power.
And as I dare not add to the Word of prophesy,
neither do I think it right to diminish anything from the
beauty of the gift I have received by disagreeable tones,
unbecoming gestures, unprofitable tautology or vain repetitions;
yet have fervent charity for them who through unwatchfulness fall into these errors,
well knowing how hard it is to steer clear of them;
and in beholding the weight and the importance of the work (in
the light of Truth) and the many mistakes we are subject to,
have oft cried out in the secret of my soul, O Lord! who is sufficient for these things;
surely only such as you makes so by your own Divine wisdom!
But I bless the name of my God,
who has condescended to rectify my spiritual senses in such a manner as to
fit me to relish the true spring of ministry through his meanest instruments,
with all the tinctures it may carry with it of
the pipe or casket through which it is conveyed.
The patriarchs and prophets all spoke with profound judgment, sense and connection,
and several of them were noted for their elegancy of speech,
as were many of our worthy ancestors,
insomuch that they came under the censure of being Jesuits,
men noted for their subtlety and learning; and.
Christ our Lord, chief Speaker in his Church, and holy pattern to his people,
was observable for his wisdom and excellency of speech,
so that it might well be said of him,
sure "`never man spoke like him`" (of Divine and heavenly truths),
insomuch that it drew this remark from the unbelievers,
"`from where has this man this wisdom and learning?`"
They were such as were strangers to that Source from which he derived his wisdom,
that thus presumptuously questioned the eternal Son of God!
And shall any now in like manner dispute the unsearchable wisdom of
God in the distribution of his own gifts for the edifying and
building up of his Church! who gives to one the word of wisdom,
to another the word of knowledge, by the same Spirit, to a third faith, and so on,
as the learned apostle has elegantly described.

But said he, "`I show unto you a more excellent way,`" that is charity,
without which he beheld himself, though endowed with all other gifts,
but "`as sounding brass and a tinkling cymbal,`"--and
indeed he gives a beautiful description of it,
well worthy the observation of you and me: "`it thinks no evil,`" said he,
and I believe it is because it would do none.
I could write more on this subject, which for brevity sake I omit.
I know not that I have given any just cause of offence to Jew or Gentile,
nor to the Church of Christ, and I thank Him who helps his children,
I can and do forgive injuries; I am not for war,
except against the three common enemies of our happiness.
Your manner of writing would have given me much trouble,
had I not seen your willingness to judge me before you
had entered into the merits of the case,
which is the most favourable construction that I can put on your hints.
For such has been my unwillingness to contend,
that I have repeatedly received the most false accusations and
bitter reflections without any answer or reply,
when I might have justified myself.

[.signed-section-signature]
Mary Peisley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Greer.

[.signed-section-context-open]
Paddock, 28th of Second month, 1752.

[.salutation]
My Dear Friend,

As you are often the subject of my thoughts,
I make you so now of my pen,
and inform you that I read your favour of 5th of eleventh month,
which was satisfactory to me, as it always is to hear from my friends.
I observe your cordial advice, respecting which I take kindly,
and have strictly adhered to it; let them be doing,
it seems my place at present to rest still and quiet,
having committed my innocent cause to the Author of my being,
with sincere desires that He may work as will contribute most to his glory,
and the good and preservation of his heritage, let me suffer what I may.
I confess they have touched me in a tender part,
by endeavouring to asperse my character but it is not my life,
which is hid with Christ in God;
had that been in the applause of men it would now be in danger, if not lost.
But oh! how inestimable a blessing it is to have a treasure laid up in heaven,
where neither moth nor rust can corrupt nor thieves break through to steal!
May you and I labour for it with all the powers of our souls;
for I am sure we have seen it in the glorious light of Truth,
to be a pearl Worth selling all for;
and in that light and sight have we clearly discovered the emptiness,
nothingness and insufficiency of all sublunary enjoyments, to make us truly happy here,
or contribute to our well-being, hereafter,
but as they were sanctified to us and consecrated to His service that gave them.
Yes, have we not begged and requested that He would not give them, except on these terms,
seeing clearly there was a curse in these very blessings,
except his blessing fetched it out.
Well, my dear friend,
do we still retain that rectified sense of things which Truth has given us,
or is not the god of this world endeavouring to blind the eye of our minds,
so that we cannot make a right estimate of things celestial or terrestrial?
for as the one heightens in our view or opinion,
the other consequently lessens and seems of but small value,
which verifies the truth of that memorable saying,
"`you cannot serve two masters,`" and that of John, "`if any man love the world,
or the things that are in the world, the love of the Father is not in him,`" that is,
it is not prevalent in his soul, for when it is, as I before wrote,
all things else are of little value in comparison of it.
But why write I thus to one who knows all these things as well as I do?
I think it is not merely the result of my imagination,
for I am oft so shut up that I can neither speak nor write of religious matters;
and not only so,
but I have felt my mind clothed with a little pain and
concern for your welfare and preservation,
as for my own,
and cries have been raised in my soul to the God of my life on your behalf,
that He might condescend safely to pilot you from that
dangerous rock whereon so many well-fitted vessels have split,
namely,
the inordinate pursuit of the worlds You know right well the havoc
this gilded bait has made amongst the lambs and sheep of Christ;
therefore let me entreat you as a sister, in love,
that you wait daily for that Power which alone can bring to silence all flesh,
and capacitate you to hear the voice of the true
Shepherd distinct from every other sound,
and if you follow it,
it will lead you out of the reach of the paw of the lion and the bear,
and deliver you from that uncircumcised philistine spirit,
which bears rule in the hearts of the children of disobedience.
It is by hearing and obeying, our souls must live to God.
I would not multiply lines on this subject, a word is enough for the wise.

May God Almighty keep you in the unity of His spirit and fellowship of the saints,
and build you up in the most holy faith.
I have some thoughts of sending this by my highly
esteemed and much beloved friend William Brown,
or his companion Samuel Neale, if they go your way soon.
I am persuaded if you retains your spiritual senses in their proper rectitude,
you will prize the company of the former, as a father in Israel,
if it be proper to give any man on earth that appellation.
May his labours of love be blessed amongst you.
I must conclude being in haste, your real affectionate friend,

[.signed-section-signature]
Mary Peisley.

--

She wrote to another of her friends, thus:

[.embedded-content-document.letter]
--

[.letter-heading]
To+++_______+++

It is not forgetfulness of my near and dear friends,
that makes me slow in my answers to them,
nor yet because I have not a singular pleasure in hearing from them;
their converse by letters or otherwise, is, next to the Divine good in myself,
the greatest satisfaction in this life; but you know, that even all of this kind,
must be through Him, who is the Source of all good, and can command the clouds,
that they shall or shall not rain.
He can stop both the upper and the nether springs, and cause a famine in the land,
and who shall say, what do you?
It is the Lord that works in and for His people,
and who shall let or hinder him from doing it His own way,
and after the manner that He sees best?
He is about to try His people every way, even as He did Israel of old, by famine,
captivity, and sore distresses, because of the hardness of their hearts,
and stiffness of their necks, in refusing to return to Him,
who had done such great things for them and their fathers.
This is the case, my friend, of people in this day, who are gone into captivity,
and refuse to return at the command of the Lord; who has long waited, and loudly called,
immediately and instrumentally, to them to return.
And for this reason, a little remnant, who like David,
prefer Jerusalem above the chiefest joy, have hung their harps as upon the willows,
and dare not sing the songs of Zion, neither can they in a strange land,
for such as desire it from them, who are of the number of those that spoil them,
and yet require of them a song, or mirth.
May all do as Daniel did, in their private chambers, set their faces towards Jerusalem,
oftener than the morning; and not be afraid to suffer for the law of their God.

It has been my lot, since my return from England,
to be much shut up as to word and doctrine,
and to sit in great emptiness and poverty of spirit,
amongst a people big with expectation of words,
and who have too much departed from the light and life of the pure Word in themselves.
And of late, since this expectation has been disappointed, and their hopes frustrated,
the Lord has often made use of me in his hand, as a sharp threshing instrument,
and put such words in my mouth for them, as they could hardly bear;
so that on all sides, the poor creature is greatly despised and rejected,
by the high and lofty professors and pharisaical righteous,
who can speak their own words, and work their own works;
and indeed I am well content so to be, and expect no better treatment,
than our blessed Lord and his disciples have met with in all ages:
we are not greater than our Master, if they persecute him they will also persecute us.
I only wish we may be found building on the same foundation,
and then the gates of hell will not prevail against us.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To R. Shackleton^
footnote:[The compiler of the
[.book-title]#Memoirs and Letters of Richard and Elizabeth Shackleton#
remarks;--'`About this time a little band,
young in years, but increasing in the experience of those things which belong to peace,
became closely united.
Amongst these, Mary Peisley, Samuel Neale, Elizabeth Pike,
Richard Shackleton and his wife, and Elizabeth Carleton, often met,
and were a strength and encouragement to each other.
Their union is expressed thus, in a letter from Richard Shackleton to Samuel Neale;
My cry was today, dear friend!
For us who are young,
who are known by one another to have good desires begotten in us for the blessed cause,
that we might be preserved, and plentifully filled with Divine wisdom,
of which I saw a great necessity,--that the Lord would take us, being children,
and teach us himself; and that we might be drawn into near unity with one another.`'
'`Samuel Neale, who had been forgiven much, loved much;
and having been obedient to the heavenly vision, became a vessel of honour,
replenished with good, and pouring it forth for the refreshment of others.
He was one, who, remembering the trials which attend youth, compassionated them;
and in advanced life, his winning affability towards young persons,
his fatherly love and care, his heart and house open to receive them,
made a deep impression on their minds, from which many received lasting advantage.`']

[.signed-section-context-open]
Paddock, 28th of Eleventh month, 1752.

[.salutation]
Dear Friend,

I have often a secret pleasure in
spiritual converse with you and others of my friends,
when my hands are employed about my lawful business;
in this I believe I have the advantage of you, your occupation, though honourable,
being such as while you are engaged in it, must, I suppose,
employ your thoughts as well as hands:
may your heart often be secretly inclined to withdraw
yourself from it and all other engagements,
to seek that which will stand by us, if we make choice of it, when all things here,
as to us, will be at an end.

Though I saw you lately on a solemn, I will not say sorrowful, occasion,
because I think the nearest friends of the deceased could hardly
regret her being taken from pain and trouble to her everlasting rest,
I had no opportunity of more than just speaking to you;
yet methought you looked like a child that had lost a mother,
or a young soldier who had had his leading officer taken away,
and he left to consider how he should make the next step to preferment.
You writes of expecting to be nursed at Kilconner,
methinks it seems high time for you to be weaned,
and come up to more manly stature than that of a sucking child.
Remember, dear friend, that many of our elders are taken away,
and some others by the course of nature cannot be expected to continue with us long,
so that the affairs of the church are consequently
likely to fall into the hands of a younger generation;
the consideration of which often deeply bows my spirit in humility and fear,
and causes frequently that cry to be in my soul,
when my Master is putting me forth in his work and service,
that was uttered by the young prince Solomon,
from a sense of the weight of his calling and his incapacity to perform it without
Divine assistance--he cries out "`Lord give me wisdom,`" or to this import:
may this be the language of our spirits while of the church militant on earth.
There seems to be a renewed visitation of Divine love in this quarter,
extended even to the outcasts of Israel and dispersed of Judah;
it looks to me at times as if the Shepherd of
Israel would leave no labour of love untried,
for the bringing home of the lost sheep.
I wish it may not add to their condemnation in the great day of account,
for having slighted such unmerited favours.
I am, through the mercy of a kind Providence, much better in health,
I hope both of mind and body.
I judge of it by the symptoms I feel, namely, a keen hunger and thirst,
and when food is administered, a good relish for it;
it being received with pleasure and thankfulness lies not undigested,
but leaves an activity and willingness to labour for more,
from a sense that the manna gathered yesterday will not serve today.
Yes, I feel a willingness in my soul either to do or suffer for His great name sake,
who has both done and suffered much for me.
I write not this boastingly; no, it must forever be excluded,
with all glorying save in the cross of Christ, and in my infirmities,
which are only mine;
I write it to the praise and honour of Him who has called me from darkness to light,
and is the repairer of breaches, and the restorer of paths to dwell in.

[.signed-section-closing]
I remain your real well-wishing friend,

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a person under religious impressions, whom she was made instrumental to help.

Does it not behove me to study your preservation,
as I am unavoidably led in the wisdom of truth to do?
It was for this end that I was chosen of the Lord at this time for your friend.
I see it clearly, and feel it perfectly;
you are to tread the same dangerous steps that I had to stumble over,
with this advantage, that she who has gone the road before you,
is made willing to lend you her hand,
and to point the snares and traps that lie in the way.
And now it is in my heart to give you a short account of my own experience,
in the work of religion.
When my soul was first thereby awakened to a life of righteousness,
I saw such beauty and excellency in the Truth,
that I thought no temptation would ever prevail upon me to turn aside in the
least degree from what I knew to be my duty and interest in the Truth;
and all my passions seemed so subjected and engrossed in
admiration and contemplation of the one great and good object,
and.
His wonderful works in me and the whole creation,
that I seemed to have no life in or relish for any other employ.
Nor could I hear with pleasure any converse that did
not savour more or less of the Spirit of Truth;
and even such as did, I delighted more in the feeling sense of it in my own heart,
than the hearing of it from any mortal: and to hear any speak of it,
that were not in the life and power of it,
was the greatest pain to my spirit that it could be tried with.

All the wisdom of men seemed foolishness to me without this,
and it is really so in the sight of God and all good men.
Alas! this state lasted not long, till my trials came on quickly,
and all my fortitude was proved; nor will I, nor dare I,
ascribe my preservation to my own watchfulness, stability, prudence or wisdom: no,
it must be forever attributed to the watchful eye of the Shepherd of Israel,
who sleeps not by day nor slumbers by night.
The enemy of my happiness strove to draw me from the true light,
and to set me upon acting by imitation,
rather than from the sense and judgment of the Truth in myself;
and here self began to plead, what need is there for me to be more mortified,
in this or that particular, than others of my fellow-labourers,
who are greater ministers, and have seen farther into the liberty which Truth allows of,
they being persons of far greater abilities than I,
and some other weak persons who make scruples of small matters?
and what is there in this, that or the other trifle of dress or behaviour?
Thus did the enemy work as in a mystery, to deceive my poor proud heart,
that liked well this doctrine of his, and would have reasoned the secret,
gentle dictates of Truth out of my mind;
not considering that the enemy was leading me to
imitate the weaknesses of my fellow-mortals,
and to overlook their virtues.

Thus did he strive in another shape and form to open that eye in me,
which had been shut to all the glory of the world, in every kind and degree of it.
All this,
and much more did the implacable enemy of my peace whisper in the ear of my soul,
and caused his agents to speak to my outward ear; yes, even some of the Lord`'s servants,
who were taken by the affectionate part, would have persuaded me from the cross,
as Peter would have done his Lord, when he said,
"`far be those things from you;`" but what was His reply,--"`Get you behind me, Satan,
you savour not the things that be of God, but those that be of men.`"
Nor is there any mortal,
that rightly and truly savours the things of God any longer than they
are under the immediate influence of His own Divine grace,
and that in a greater or smaller degree as they partake of it;
let us therefore cast this part in all the disciples behind our backs,
and look to Him with a single eye, who was never overcome in battle.
He it was, who let me see that no mortal could be a perfect pattern to me, in all things;
and that He would lead me in a manner different from most others,
both as to my gift and conduct.
And though the manner in which Truth led me was often misconstrued,
and wrongfully censured, as the object of pride, singularity, temper, etc.,
my God knew it was in obedience to Him,
and in refined love and charity to my fellow-mortals, which would not nor dare not,
draw the hearts of the people from their true King, as Absalom did,
who perished for the same.
And those innocent practices in converse and behaviour,
which I saw used by others of my sex and condition, whom I preferred before myself,
were to me forbidden, though they might be to them lawful, and for what I know allowable:
especially towards the other sex, I found it my duty to act with the utmost caution;
if I found no danger on my side,
yet I saw it needful to consult the good of those with whom I conversed.

And had I not been obedient in this particular,
I am sure I should not have been preserved till this time,
to have been your friend in the Truth, as I am this day;
my own affections and the affections of others,
would long since have stolen me out of his hands,
who has an absolute right to dispose of my body and spirit, "`which are His.`"
Such was the prevalence of the general love and esteem, that I met with for a time,
which naturally drew my mind, and the prevalence of the love of God,
which powerfully attracted my soul towards Himself from all fading objects,
that between these two powers, my mind was, at times,
in that position that Absalom`'s body was,
when he hung in a dying condition in the boughs of a tree, as between heaven and earth,
scarcely knowing which power would have me:
but as there was a faithful obedience to the voice of the true Shepherd,
I found the power of Saul grow weaker, and that of David stronger.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Shackleton

[.signed-section-context-open]
Borris, 13th of Third month, 1753.

Though I am poor, low, distressed and afflicted,
having more need to be ministered unto than to minister to any,
yet as you have repeatedly desired to hear from me by word or writing,
I now feel a secret draught to let you know a little how it fares with me;
though the source or cause of my sorrow must forever be concealed from all mortals,
and pent within the narrow confines of this troubled breast:
save when admitted to pour out its complaints in the
bosom of my never-failing Friend and blessed Redeemer,
all other counsellors are denied me,--may He
condescend to direct my steps in righteousness,
and then all will be well.
Let it suffice to say, that I have just been in silent and solid retirement,
considering my awful calling,
and comparing my life to that of the Captain of my salvation,
who was made perfect through suffering;
and shall I dare to say my life bears some faint resemblance to His?
yes, surely, as well indeed it may, who am called to be his minister.
He was a man of sorrows and acquainted with grief: so am I,
a woman of a sorrowful spirit, that have moved my lips in prayer,
when my tongue could not set forth the anguish of my soul,
pouring it forth in broken accents, sighs and groans,--not for riches, honour,
name or fame, nor yet a mortal earthly love, or for a first-born son after the flesh;
but for divine wisdom, heavenly instruction,
and ability to bring forth fruits of righteousness to the
praise and honour of Him who has called me to glory and virtue.
Was my Lord despised and rejected of men?
So am I;--Hannah like, I have been misunderstood, even by the high priest;
but not by the great One of our profession, who knows and regards His own,
gently whispering in the ear of their souls, "`Fear not worm Jacob, I am with you,`" etc.
My Lord was betrayed: so have I been by a professed disciple.
He was left alone in extreme agonies,--none to aid Him,
or to make his complaint to, but the Father alone.
So have I.
Let me not longer dwell on this copious subject,
than I find the strength of His love to comfort my mind,
and then I might forever dwell on it, and find new wonders in it.
O! the length, the breadth and the unfathomable depth of it!

I observe your complaint of poverty, which was no incitement in me to do the same,
had it not been my state, and I thought it might not be discouraging to you,
to know that you shares the same lot with your brethren and sisters.
Do you seek great things for yourself?
seek them not; for the Lord has said, that He would bring evil upon all flesh;
but if we have that promise which was given to Baruch,
"`your life shall be given you for a prey wheresoever you go,`"
may this be our happy experience to save our spiritual lives;
this seems to be the ultimate of my wish, expectation or desire,
in this calamitous day and time we live in as to religion.
The priests, the Lord`'s ministers mourn, the virgin daughters of Zion are in bitterness,
saying with Baruch, "`the Lord has added grief to my sorrow.`"
Well, let me not dwell longer on this theme, but hope for beauty for ashes,
the oil of joy for mourning, and the garments of praise for the spirit of heaviness;
how does this holy anchor keep my troubled soul
from foundering on the quicksands of despair.

Tomorrow, if Providence permit, I am to go to Mountmellick,
where I believe my concern for America will be made public.
Oh! how complicated are my exercises;--but do not think from
what I write that I go murmuring and whining after my Captain.
Oh! says my soul, may I always count it an honour to be found worthy of His commissions;
yet, Oh! this self does not like the repeated strokes of the hammer,
which the vessels of beaten gold in the Lord`'s house must undergo!
Where will my pen carry me?
shall I a worm presume to think myself one of these?
yes, surely, I have passed seven times through the furnace of affliction.
I wish there may at last anything remain that is of the pure solid weighty gold!
But let me say before I conclude, that there is a secret faith lies hidden in my heart,
that when this bloody baptism is over, my God will cause me to go on my way rejoicing,
I know I must, as my Master did, descend before I ascend.
Do not forget me when you are in your best clothing;--my dear love is to yourself,
wife and mother; in which I remain your assured friend,

[.signed-section-signature]
Mary Peisley

--

The religious concern just mentioned, which had at times, for years rested on her mind,
to pay a religious visit to the churches in America,
continued to impress her with additional weight; the baptisms she passed through,
to fit her for this work, she thus further describes:--

[.embedded-content-document.letter]
--

"`The Lord was pleased to bring me exceedingly low, both in mind and body,
the latter so much so, that my life was despaired of by myself and others;
and such was my exercise of mind and pain of body, that life seemed a burden, yes,
I was ready often to wish my body dissolved, that I might be with Christ.
Yet when death looked me in the face,
unaccompanied by that which alone can render it supportable to human nature, namely,
an incontestable evidence of eternal rest to my immortal spirit,
it appeared to me a gloomy prospect, and the cause of its being so I believe was,
that my time was not yet come.
For I knew not that I had wilfully offended the Divine Being,
that should cause him to withdraw His life-giving presence,
and allow my mind to be clothed with a thick cloud of darkness.
During this time of trial and deep exercise of body and mind,
the Lord my God was pleased to extend His mighty Arm of power,
and reduce my spirit to a calm,
so as to make His holy voice intelligible to my weary distressed soul,
and to inform me that He would raise me from that low and dark state, and cause me,
in his love, to visit the churches in America the next year.
And although this seemed to clash with my temporal interest,
as well as natural inclination, there was at the same time when I heard the call,
an entire resignation wrought in my mind, so that I could say indeed and in truth,
"`Your will be done in all things,`" which was to me a
confirmation that the thing was of the Lord,
verifying that saying of David, when addressing the Almighty, "`In the day of your power,
your people shall be willing;`" and such was the prevalence of it,
that it removed those things which had been like mountains in my way,
and caused them to be cast into the sea of annihilation.
This journey had been before me, by distant views,
from a short time after my receiving a gift in the ministry.
There were many difficulties seemingly insurmountable in my way,
which the Lord in his own time was pleased to remove; so that I may say of a truth,
I was brought through the furnace of affliction to perform this journey.`"

--

She corresponded with her friend Catharine Payton,
who felt a like concern to visit the churches in America,
and great was the sympathy they had with each other.
Mary Peisley left home the 22nd of the third month, 1753,
attended the quarterly meeting at Edenderry, and went from there to Dublin,
where she met with considerable trials by opposing spirits,
of which she says she had a previous sight, and thus writes:

[.embedded-content-document.letter]
--

"`I felt the power of darkness at work, so as grievously to oppress my spirit;
but by degrees it was cast down, and the pure light prevailed.
The design of the enemy was, to prevent my intended journey by raising contention; which,
blessed be the name of God, he was not able to do.
I left Dublin in the fifth month, in love and unity with my friends,
and good desires for my enemies, if any such I had; and landing at Liverpool,
got safe to London.
After attending the yearly meeting at London,
I went to the yearly meetings of Colchester, Bury, Woodbridge and Norwich;
all which were attended with a good degree of the life and power of Truth,
and an honest labour for the good of the people.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Pim

[.signed-section-context-open]
London, 24th of Seventh month, 1753.

[.salutation]
Dear Cousin,

Yours of the 22nd ult., I received at Norwich,
which was satisfactory to me, and the contents observed;
being what is necessary for me and all that would be
Christians in reality to be found in the observance of;
and especially in these perilous days, wherein so many bad examples abound,
and many strange voices are to be heard to allure from the voice of the true Shepherd;
who says in the secret of the soul,--"`This is the way
walk in it;`"--a way of mortification and self-denial,
a way to which corrupt nature is above all others most averse, and seeks to shun.
I need not dwell on this subject, you know it better than I can inform you,
I shall therefore proceed to give you some little account of how it fares with me.
As to my health I am through Divine favour much better than heretofore,
and as to my mind I do not remember ever being more empty,
stripped and destitute than of late;
yet at times witness a little strength to perform the
duties which I believe are required of me,
and am forced to walk by faith more than by sight,
having at times scarcely light enough to see
where to set a foot in the spiritual journey,
and then if faith fails, I am obliged to stand still.
Yet in all these low times and trying seasons,
I have not hitherto been permitted once to doubt of my being in my place in coming here,
or in the little turn I have taken in this nation;
though it did not appear to me till a short time before I went,
and the impulse for it very gentle.

I found it difficult to get clear of that great city, Norwich,
or rather the inhabitants of it, both Friends and others.
I was obliged to make a visit to a large congregation of the
people called Methodists at their place of worship,
who behaved with great moderation,
and some of them discovered a Christian love and tenderness;
their speaker left the assembly to us, sat quietly by us all the time,
and bid us act according to our freedom, which led us to silence for near an hour,
a thing I believe very uncommon to them,
and indeed it was remarkable the stillness which they were brought to,
more so than many meetings of Friends that I have been in:
and in some conversation with their preacher, so called,
he assented to the truth of the necessity of silence in their places of worship.

Eighth month 2nd.--Here I dropped my pen,
in order as I thought to give you some account of our embarkation,
but am still at a loss about it;
my companion has been very poorly in health most part of the time since I left her,
and is in no way fit to go to sea, being very weak.
And was not this the case, I cannot find my spirit clear of the inhabitants of this city,
nor my way open to leave it.
I have been a good deal tossed about my stay,
considering the season of the year is passing over;
but I am now through Divine favour resigned to stay the Lord`'s time,
which I have a secret hope he will show us.
I had for a time lost sight of Charleston, but I think I have again had a review of it,
to which port there is likely to be a passage at any season of the year.
Dear cousin, I wish I may be found worthy a place in your remembrance,
when admitted to intercede for yourself and the flock and family of our God.
I am sure you are often near to my mind in the uniting love of our heavenly Father,
in which I conclude your affectionate cousin,

[.signed-section-signature]
Mary Peisley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth Carleton, Dublin.

[.signed-section-context-open]
London, 28th of Seventh month, 1753.

[.salutation]
Dear Betty,

Having this morning a little
leisure from the necessary cares for my journey,
retired alone to meet the beloved of my soul and to converse with Him,
in whom my spirit delights; who was pleased to appear in his ancient goodness,
as a morning without clouds with a fresh shower of celestial rain to my thirsty soul.
At this season you and many more of my near and dear friends
in my native land were sweetly brought to my remembrance,
in the soft sympathy and union of spirit,
which neither length of time nor distance of place can wear out, nor any evil power,
men or devils dissolve, as there is a keeping to Him who is the Author of it;
though there may be for a time an interruption,
which is indeed painful to the right-minded, and rejoicing to our enemy,
who seeks daily to effect this work, because he knows our strength lies in unity.
I have no answer to my last, save what I saw in a letter to my companion,
but I would not have you attempt to write to me, or any other,
without a proper opening so to do, I mean on religious subjects;
for I think I have seen more clearly of late than ever, the danger and hurt of it,
and have been made to look upon the practice as next a-kin to a false ministry,
if not worse; because it remains for review,
and may with the better connection be packed together as to form of sound words,
yet without sense or feeling of what we write,
and therefore can convey none to those who read it:
though it may sound and tinkle to the outward ear,
it is a waster of strength and a diminisher of life;
one of the ways of stealing the word, which the Lord our God is against,
and will plead with His people for.
This my dear friend has made me keep silence to those who are near and dear to my life,
and with whom I truly sympathize in the fellowship of the gospel,
and travail as in birth, with pangs of spirit unutterable,
that Christ may be perfectly formed in them, and they found complete in Him,
lacking nothing of what he would have them to be;
which experience I have found it hard to attain to, yet think I may say with David,
in reverence of spirit before Him, who works all my works in me and for me,
and who shall forever have the praise,--"`my heart is not haughty nor my eyes lofty;
I have not exercised myself in things too high for me; I am as a weaned child.`"
Weaned indeed I am, and strive to be,
from all that is near to my nature or desirable to the creaturely part,
shutting out of my thoughts those that are most pleasing to them,
save when I can remember them for good, that is,
when they are brought to my remembrance by the pure
Spirit which is without mixture and thinks no evil.
And as to the use of my natural faculties,
I think I never knew them in greater subjection than at this season;
it seems as though I was not to have the use of them, even in civil affairs,
but by Divine permission, and in such a degree as He pleases who gave them.

And as to my public appearance,
I never knew it to be in so simple a manner in my own view,
finding it my duty at times to rise and speak without a
word in my mouth but as it is immediately given;
so that there is no room for me to be exalted with gifts, nor do I desire it,
if so be I can but witness a degree of the power which first put me forth,
and caused me to stand trembling before the people; which,
blessed be the name of my God I am at times a witness of,
though in this appearance can only be acceptable to them who abide in the same:
to the worldly wise I am but a fool and my preaching foolishness,
with which I am content, and only wish to be enabled to bear the cross,
it being the way to the crown.
If you have freedom shall be glad to hear from you before we leave England,
with as full an account of Friends and affairs of Truth as time and ability will permit.

[.signed-section-closing]
Yours as usual,

[.signed-section-signature]
Mary Peisley.

--
