== Chapter V

"`After we had spent some time in this quarter, and visited Friends generally,
eastward of Boston as far as North Yarmouth,
on my return I found my mind secretly drawn towards a separate people,
at Hampton in New England;
but as it was a service likely to be attended with more than common difficulties,
I waited to have a more clear sign and stronger evidence of my duty,--which the
Lord was pleased to give me in His own time,--He knew the sincerity of my heart,
and that I had no will to disobey Him.
We passed the place fourteen miles,
before I received such a satisfactory evidence as I had wished for;
in which I believe there was wisdom,
as some Friends might perhaps have judged me as being too
forward on entering on a service of such weight and difficulty.

"`At Newberry, where were Friends from several meetings,
I found my mind so strongly drawn, and with such weight towards this people,
as rendered me quite unfit for any other service,
it seeming impossible for me to think of any thing else in that meeting,
except laying my concern before Friends there;
this I was fully persuaded was what Truth pointed out to me.
Accordingly at the close of the meeting, I requested the most solid,
concerned Friends to stay; when I told them how it had been with me,
they readily agreed to my going, and several gave up to accompany us.
My companion at first seemed affrighted about going, and wept considerably;
I left her quite at liberty to stay or go, and in the morning she found her way open,
and she had good service.
They received us with much seeming kindness,
particularly one who appeared to be like the head of them,
and was the person whom I chiefly wanted to see.
He spoke many fair words to us before the meeting,
and told us that he looked upon it as a favour from the Lord, that we were sent to them;
but after meeting, when I came to tell him my mind freely,
and deliver the message which I had to him, he soon changed and treated me roughly:
declaring that I would not find mercy with the Lord,
until I repented of my proceedings against him
and them at the Quarterly meeting at Hampton.
We had a seasonable opportunity to ease our minds,
in which our Master was with us by His Spirit and power.
I was made sensible that there was in that place a people,
sincere in their searches and endeavours after religion, which the Lord regarded,
though under many delusions and mistakes.

"`In this quarter (New England) close and hard work fell to our lots,
amongst those who called themselves of our Society;
this work was difficult to be accomplished, because many thought themselves whole,
while in reality they needed a physician,
manifesting an unlawful familiarity with the world.
Unbounded curiosity in the people caused meetings to be thronged,
so that in hot weather it was exceedingly hard to sit them,
and much more trying to speak in them but He who searches the hearts of all,
knows their intentions, disappointed these wrong spirits,
by closing our mouths in silence one meeting after another;
which greatly displeased the people, and drew upon us great reproach, lies and slander,
all which we were enabled to bear patiently, and to rejoice in, for our Master's sake.
We were led to endeavour to separate those under our name from others,
and at times some of the ruling members from the rest,
to whom we had very close things to offer,
feeling that the declension which so glaringly appeared in the Society,
had reached in many instances even their borders.
This seemed a very hard task to get accomplished
because of their being so connected in marriage,
etc., and the discipline being so sadly let fall,
that they knew not who were or who were not proper members.

"`In some places we had to visit particular families,
before we could cast off our burdens, as in Boston;
where I was led to find out some hidden works of darkness,
the workers whereof ought to be cut off from the name and Society of Friends,
in order to clear it and them from the scandal they brought on it.
There was one young man in particular,
with whom we had to treat on his being likely to marry with one of another society;
it arose in my heart, while we talked with him, that he was deeply tinctured with deism,
a disbelief of the Scriptures, of the coming of Christ in the flesh,
and His second appearance by His Spirit.
I told him my opinion of his state, which he acknowledged to be true;
he spoke in defence of his opinion.
I told him the ground which his unbelief sprung was leaning to his own understanding,
and departing from the Light, which alone can convince of God and godliness.

"`I left some parts of this country not quite clear in my spirit but under a weight,
and particularly Newport; I was given up in my mind to return to it,
but could not then find my way open;
I was advised by a Friend to leave it for the present; I did so,
and travelled under great exercise of spirit through Connecticut,
but without condemnation.

"`At Oblong,
I had a sight that my dear companion Catherine Payton and I were to separate,
for the work's sake:
I had been at times much straitened in my service by preferring her and her gift;
for I was greatly afraid and jealous over my own heart,
lest self should have any part in our separation,
from a desire of appearing greater than with a companion.
Another thing which appeared to me with considerable weight, was her youth,
and the many dangers that might attend if not rightly suited with a companion.
These and many other considerations, would I believe have prevailed,
had not the Lord laid his "`hand upon me, in a remarkable manner, on this wise.
My mind was stripped of ability for service,
and deeply bowed to the Centre of all strength for instruction;
in which state I had a desire given me, to be at Philadelphia,
and to go there pretty direct without appointing many meetings.
Accordingly I desired that not more than two meetings, which lay in the way,
might be appointed; but my companion and some other Friends,
encouraged the appointing of more.
I became passive, though I found my exercise for meetings in those parts,
was at that time taken away: which afterwards more clearly appeared,
having been silent in all, except one I found freedom to have appointed;
neither was my companion capacitated for the service in the last meeting,
which was at Long-reach on the Main.`"

+++[+++It was with the concurrence of Friends that she and
her companion thus separated for the work's sake.]

From a very concise account kept of her gospel labours in this land,
she appears to have been closely engaged in visiting
meetings mostly in the province of Pennsylvania,
from the tenth month, 1754, to the spring of 1756.

Within this period she wrote the following letters, which have been preserved.

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel Fothergill

[.signed-section-context-open]
Wright's Town (in America), Second month 27th, 1755.

The freedom and candour of your very acceptable favour has had the
happy tendency to set me upon the strictest examination of myself,
which my deceitful heart was capable of;
a task to which it was much disposed before the receipt of yours,--it being
with me a season of emptying and cleansing,--a state and dispensation,
which I pray with my whole heart, that neither you nor I may ever get above,
and especially so when we are much engaged in our Master's work;
for it seems to me next to impossible that we should escape some little spots and stains,
though we may be ever so careful of our clothing, and wrap it ever so closely about us,
it will get a little soiled by being used every day.
I am sure mine does so, and if I should hinder my Master from stripping it off,
and washing both them and me,
I should before now have made but a very mean appearance in
the sight of Him who sees through every false covering,
the veil of flesh and all its seeming excellencies;
for He beholds no beauty nor comeliness in any thing that is not derived from Himself,
who is the only unmixed fountain of light and purity.

And what does it signify, my dear friend,
if we appear naked and empty in the view of a set of mortals,
who are unacquainted with the Lord's ways and doings?
I think I have beheld in His light,
and been informed by the instruction of His pure Spirit,
that I have never been more amiable in His sight,
nor attracted a greater degree of His love, than when my spirit has been quite unclothed,
not only of my own righteousness, but also of the rich jewels of His grace,
and have wandered about as in sheep-skins and goat-skins, destitute, afflicted,
tormented, in a spiritual as well as a natural sense;
nor have I ever had such near fellowship with the martyrs, apostles,
and fellow-sufferers of Christ, as in this state.
My health, through Divine favour,
has been continued to me since our parting to this time,
except some bad colds occasioned by the sudden changes of weather.
As to my labour or services in the Church, I can say little;
I think them very mean and low,
yet hope I shall endeavour to be faithful according to my measure.
I desire your care and good wishes for me, and as much freedom with me,
as Truth will allow of; which I know will always be well received,
while I remain in that charity which bears all things.

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Shackleton

[.signed-section-context-open]
Philadelphia, 13th of Twelfth month, 1755.

Your acceptable letter, perhaps might have been acknowledged sooner,
had I not a hope or expectation of seeing you before now:--hope did I say?
alas!
I should have none, but in doing and suffering the will of God;
all other seems forbidden, and are through Divine favour, pretty much restrained.
My stay being prolonged in this country, has been altogether unexpected to myself,
and I have been held in such uncertainty for some months past,
as not to be able to give my friends any information respecting future movements.
I have stood as a soldier waiting for the word of command,
to march whithersoever my holy Leader may be pleased to direct;
and I may say to the praise of His great name, that He is not a hard Master,
but good and bountiful every way.
For though I have, as recited,
been kept as a day servant in a kind of undetermined state in regard to our stay;
yet I may say of a truth,
that I do not remember ever to have had such a degree of steady peace,
and holy unmixed quietude of mind, so long together,
amidst many close deep trials and exercises in
religious duties,--some have been of such a nature,
as I had not been tried with before, and which required the utmost fortitude,
wisdom and patience.
There is here the old pharisaical spirit, which I have heretofore had to war with,
and it seems to love me no better than usual.

I shall now proceed to give you a narrative of the manner of my stay; to do which,
I must begin with an unlooked for prospect set before me the summer after our landing,
and which has rarely, if ever, wholly disappeared.
How it may be, I cannot at present foresee: but this I know,
that it has proved as ballast to my mind, with respect to going homewards this fall;
as also a means to separate me and my dear companion,
which I believe was in the wisdom of Truth.
It was presented before last fall, with a draft to this city;
so that I was ready to conclude I must have gone
before my visit to this continent was ended,
I mean to one or more of the West India islands.
I waited some weeks in this city,
wrapped as in a thick cloud as to any light which way I should turn,
whether home or elsewhere: to appoint meetings any where on this continent I dared not,
till the light went before me;
having attended some that were forwardly appointed without my directions,
till I was become as a sign and wonder to myself and others.
At length I felt my way opened,
to finish my journey on this continent separate from my former companion;
which I was assisted to perform with some degree of satisfaction to myself,
and I hope some little edification to the churches.
In the latter part of this journey,
it pleased my good Master to bring me under the most severe baptism and crucifixion,
that ever I knew in the course of my religious experience, partly on my own account,
and partly on the account of some,
to whom I had been made a minister and instrumental to
help into the way of life and salvation;
who, looking at the creature more than the Creator,
(who is worthy forever,) became entangled, as a lamb caught in a thicket.
It was then that I felt the depth,
and true meaning of that emphatic saying of the holy apostle,--"`My little children,
for whom I travail in birth till Christ be formed in you.`"
And oh! the pangs and throes, the sighs and groans,
which a mother in Israel has to pass through and put up; and what if I say,
it is something like the suffering which the Captain of our salvation passed through,
in bringing many sons and daughters to glory.
It is with the utmost reverence and fear that I make the comparison,
between Him and His ministers,
who are to fill up in their bodies that which is behind of His sufferings.
But I seemed to myself, and was as one nailed to the cross, day and night,
for weeks together,
with this desire or prayer fixed in my heart,--"`Let me not come down from the cross,
till the glorious design be fully accomplished; that so your will may be done by me,
in me, and upon me, in time and in eternity;`"--and truly the baptism was not removed,
until this became the happy situation of my mind,--that to live or die,
to be in health or sickness, in prosperity or adversity, in Europe or America,
in France or Spain, to pass through good or evil report, in the will of God,
seemed just the same to me.

I write not these things boastingly, but to the glory of God.
You and others know what I am by nature, that in me, that is, in my flesh,
dwells no good thing.
This was the necessary preparative for the fore-
named state of peaceful serenity of conscience,
in a situation to which nature is above all things most averse,--namely,
daily dependence and uncertainty, being indebted or obligated to another for support,
having nothing that it can call its own, save weakness and infirmity;
and this is that glorious mystery, and seeming contradiction,
which the holy apostle speaks of, in having nothing, and yet possessing all things.
In this situation of mind I entered this city; and having looked around me every way,
with resignation to turn as I might be drawn by the power of matchless love,
and hoping from the looseness which I then felt from all parts of this continent,
that I might be permitted to return home with my brother, (who I had heard was in town,
and likely to sail soon,) even if my companion could not go with me;
yet it was with this prospect, that I might probably have to return to this country,
if life was spared, and I knew not how soon.
On coming here, I found that my brother was gone,
and my companion not clear of this continent; so I concluded to wait for her a few weeks,
or if it might be months,
she expressing uncommon concern at the thoughts of being left behind.

During the time I waited for her,
some Friends proposed to accompany me in visiting part
of the families of Friends in this city,
a service which had several times been presented to my mind in the course of my journey,
yes, before I left London; and when the proposal was made,
I found a perfect freedom to join with it,
it being with the concurrence of the monthly meeting,
little supposing I should be held to it in the manner I have been;
but it is a service which the Lord has been pleased to bless in a remarkable manner.
I have been in 160 families, and attended six meetings every week while in town,
as health permits; besides visiting the sick and afflicted,
and taking some excursions to the country.
My companion when she came to town, being sometimes poorly in health,
proceeded but slowly; we now go together, having tired most of our companions,
besides a couple of men Friends, who go to show us the doors,
and be witness to our labours; there are nearly as many yet to visit,
as I have been with.

Whether I shall go this winter, or ever, to any of the islands mentioned,
is at present hidden from me;
but had not the prospect afresh opened after I had been here some time,
I think I dare not have admitted the thoughts of staying this winter.
But I have been blessed with seeing, yes,
have been made instrumental to help back some of the before-mentioned lambs to the fold,
one, in particular in this city, who I hope may be made a serviceable instrument.

I have now given up expectation of seeing my native land before the spring;
at which time I hope to have the company of our
beloved friend Samuel Fothergill on ship board:
he is now in the city,
also John Churchman and several other Friends on the affairs of the Society.
It is a difficult time to Friends in these parts,
who are concerned to keep up their Christian testimony against wars and bloodshed:
and especially to such as are concerned in state affairs.
I have had my health better than common in this city,
for which blessing with all others that I am an unworthy partaker of,
I desire to be humbly thankful.

[.signed-section-signature]
Mary Peisley.

--

+++[+++It appears that Mary Peisley, with her companion Catharine Payton,
and also Samuel Fothergill,
(then in America on religious service,) were made instrumental
of much help and comfort to Friends in Pennsylvania,
and some neighbouring States, who were under great alarm from the inroads of the Indians,
some of whom had been engaged by the French in
the war then existing between England and France.
These Friends were earnestly and affectionately concerned to promote peace,
and to exhort Friends to remain faithful in the support of their Christian testimony;
to abide in their tents, and not so much as to look outward,
but to avoid and keep clear of every thing contrary to
the peaceable spirit of the Gospel of Christ,
and thus to show themselves His true disciples.]

[.embedded-content-document.letter]
--

[.letter-heading]
To John Pemberton of Pennsylvania

[.salutation]
Respected Friend,

I have read and considered your letter,
and cannot help thinking that the temper of mind
you discover deserves some encouragement,
which I am willing to give as far as is in my power.
In the first place, I would remark to you,
without the least intention to lessen parental authority or filial obedience,
so far as they are either lawful or expedient,
that many parents of this age have bent their thoughts and desires too much to earth,
to have a clear and distinct discerning of the times and seasons in a spiritual sense,
and of the sacred purposes of Him, whose wisdom is inscrutable,
and whose ways are past finding out by all the penetrations of finite understandings,
uninfluenced by His own eternal light:--even then,
we see and know but in part while here.
But some of us have believed and seen in the visions of light,
that the day of gospel light which has dawned will rise higher and higher;
notwithstanding that some clouds may at times have intercepted its beauty and brightness,
as has sorrowfully been the case amongst us, a people who have been highly favoured.
And though I have not the least intention to derogate from the
real worth of those honourable sons of the morning,
who were made instrumental, in a great degree, to break down the partition wall,
which carnal selfish men had erected, between the people and the Sun of Righteousness;
yet I am not afraid to say, and give it under my hand,
that it was and is the design of God,
that His people in future ages should make an improvement on their labours,
and carry on the reformation even further than they did.
And notwithstanding a night of apostacy has come over us as a people,
(as day and night naturally succeed one another in their season,
and God keeps his covenant with both,) yet am I of the judgment,
that that day has begun to dawn,
in which the Sun of Righteousness will rise higher and higher,
and with greater lustre than heretofore.
But if those who are called of God to be the sons of this morning,
look back to the night, and to them who have slept and been drunken in the night,
(by sipping of the golden cup of abominations,) or even to the latter day,--
they will frustrate the designs of Providence respecting themselves,
though not respecting His own work.
For it is His sacred determination to be glorious in heaven and glorified on earth,
though these who would be called His Israel be not gathered.
And I am of the faith, that where the gospel has first been preached to them,
as it is fitting it should, such as neglect to embrace it,
thereby rendering themselves unworthy of so great salvation, will be left,
and the feet of the messengers turned another way, even to the highways and hedges,
with a power of compulsive love, which will prevail on the halt, the maimed,
and the blind, to come to the marriage of the King's Son;
and by coming they shall be made strong, beautiful, and lovely,
as a bride adorned for her heavenly husband,
who shall not look back to those things that are behind,
but press forward toward the mark for the prize of the high calling of God
in Christ Jesus,--following no man's example further than they follow Him.

And what if I say in the faith that is given me,
that God has designed to carry some of this generation, in these parts of the world,
higher and further in righteousness than their forefathers were carried,
even such as were honourable in their day, and are fallen asleep in Christ.
Therefore let them take heed that they limit not the Holy One of Israel,
nor circumscribe the leadings of His blessed unerring Spirit,
by looking too much at the example of others;
for this has been a means of stopping the gradual progression of many glorious,
well-begun reformations.
Instead of going forward, they have looked back,
and even sunk below the standard of the first reformers.
Such as will be the happy instruments to labour for a reformation in this degenerate age,
must differ in their trials from the sons of the former morning,
and will find them to be of a more severe and piercing kind:--theirs were from the world,
and such as they might justly expect therefrom,--not exempt from false brethren;
ours will chiefly arise from those under the same profession,
clothed with the disguised spirit of the world,
and that amongst some of the foremost rank (so called) in Society: and what if I say,
(though my natural eyes may not see it,) that God will divide in Jacob and
scatter in Israel before that reformation which He designs is brought about,
in His Church.

In regard to the matter proposed by you, I shall answer briefly,
without entering into the debates on either side, and say, that I am of the judgment,
that if you stand single and upright in your mind from
all the false biasses of nature and interest,
stopping your ears to the artifices and pretexts of self-love,
with all the fallacious reasonings of flesh and blood,
and the subtle whisperings of an unwearied enemy,
you will find it more safe to suffer with the people of God, than to enter on,
or undertake doubtful things, especially when you considers the use which has been,
or may be made of that tax +++[+++for the support of war.]
I had not the least view, when I took up my pen, of enlarging in the manner I have done:
but I felt my mind unexpectedly opened,
and feel a perfect freedom to allow you to show this to such of your acquaintance,
as may be in like situation with yourself, that is, undetermined:
not however that I want to expose this,
with any other view than to strengthen the minds of the weak and wavering,
and if it might have the same service, I had rather my name should be concealed.

In a degree of that love, which seeks the good of all,
I conclude with respects to you and the family, in which my companion joins,
your well-wishing friend,

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth Carleton,^
footnote:[She was married to Richard Shackleton the 17th of tenth month, 1755, his second wife.] Dublin.

[.signed-section-context-open]
Stanton, near Philadelphia, 4th of Seventh month, 1755.

[.salutation]
Dear Friend,

Your kind favour of the third month I received last week,
and feeling a draft of love with a desire to salute you in it, I have taken up my pen,
not knowing what may be given to add,
save that I find an inclination to acquaint you a little how we have fared,
as Truth may open my mind so to do, if I am near enough to it to be aided by it.
And in the first place I may inform you,
that I think I have nigh finished the most dangerous painful
journey that ever I undertook;--dangerous and painful indeed
it has been to both body and mind beyond expression,
or conception of such as have not trod the same trying steps,
through paths not much frequented, where few footsteps of this generation appear;
and those ancient worthies seem almost worn out of the minds and memories of
many professing the same eternal way of Truth which they did.
But alas! how widely distant and sadly removed are some from it,
and many have even lost the marks of the meekness, humility, Christian zeal and charity,
with a patient suffering for the cause of God,
though filling their seats in the visible Church.
And here I am stopped from a humbling sense of my own weakness
and unworthiness to be compared in the least degree to the
valiants and nobles of the morning of this latter day;
yet I have been ready to conclude at times, that the trials and sufferings of a remnant,
who are honestly engaged to be faithful in their measure according to knowledge,
are more trying and dangerous in their nature,
than what those sons and daughters of the morning had to meet with and pass through.
The latter had the winter and storms of adversity in the outward to meet,
which had a tendency to drive to the Rock of Ages,
where they found the warming rays of the Sun of Righteousness
in the day of God's visiting power and summer season of His
love and ingathering virtue:--their enemies were outward,
that is, from the world, where they might expect them,
open and manifest to the eye of reason.
But ours are often secret enemies, hidden,
and concealed from every eye and understanding, but that which Truth opens;
and they often secretly smite in spirit and fight against the testimony of
Truth which is delivered in the plainness and simplicity of it,
and which comes not with enticing words of man's wisdom,
calculated to tickle and please the curious outward ear, while the soul is starved,
that immortal part which cannot feed on chaff or wind,
but which seeks in the ministry solid, sound, plain, substantial truths,
such as agree with the experience of true believers,
and the present state of their minds.
This kind of doctrine is too much out of use in America, as well as Europe;
and instead of it,
a sound of words which abounds amongst them,--words sound in themselves,
but destitute of life and power,
not suiting the states of the people (who want not to be amused with words,
but aroused from their sins),
nor proceeding from a feeling sense or experience of what they speak.

I have dwelt much longer on this disagreeable subject than I expected when I began it,
or may seem necessary to you, who are not (that I know of) concerned that way;
but when it is considered that I have painfully felt it as one of the
greatest sores and wounds in the Society with which I am embodied,
it will not be wondered at that my thoughts and pen run
upon it when relating to a friend how I have fared.
And now to return to the subject matter of comparison;
we are in the summer and warm sunshine of worldly prosperity, peace and plenty,
which has a natural tendency to draw from the Rock, and lull to sleep in the present,
mean, miserable, and transitory enjoyments of this life; while as regards the inwards,
it is a winter season, a day of darkness, gloominess and sore distress; yes, famine,
faintness and weariness of soul sometimes seize those who are
made to see and deeply feel the state of the Church in general;
though in some respects there is cause of rejoicing,
and we have been favoured to see a little of the fruits of our painful labour,
and perhaps more may yet be discovered in the Lord's time.

I told you that I thought I had well nigh finished my journey in this country,
and so I hope it is;
for I hardly think I shall have to appoint another meeting while in it this time;
yet I cannot see when I shall be fit to leave it.
My companion has not quite done her journey; and except I really believed it my duty,
I cannot think of leaving her behind.
Through mercy our love for each other is not decreased by our separation,
but much otherwise;
and it is no wonder that we should be made more near and dear to each other,
considering how much we have been led to the same track of suffering since separated,
as well as together.
This indeed must be the case with all them that know a growth in the Truth;
their love in it for each other will increase, though the ties of natural affection may,
by length of time and absence, in some degree be weakened.
This I think I have known respecting some in my native land.
I hope I lack not natural affection,
but my love for them in the pure innocent life of Truth has been much strengthened;
though I have neither a will nor power to say so much to some of them by writing;
they are as epistles written in my heart by the handwriting of Truth,
which alone will stand the test of all events that may happen in the ordering of it.
Dear Samuel Fothergill and Joseph Dickson have been great
helps and comforts to us in their work and service,
and are nearly united in spirit, particularly the former,
whose tenderness and regard towards me I cannot but admire with love and esteem.

I shall now conclude with the salutation of true love to you, your family, etc.,
and as many of my friends as you may be free to communicate it to,
with the intelligence of my health, which is as well as I can reasonably expect.

[.signed-section-closing]
Your friend in the Truth,

[.signed-section-signature]
Mary Peisley

--

After her return from America she attended the National meeting in the eleventh month,
1756, and returned a lively account of her journey.

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth Shackleton

[.signed-section-context-open]
Russetdown, 28th of First month, 1757.

[.salutation]
Dear Friend,

My bodily health is through Divine favour bravely restored for the time,
considering the violent disorder which I have so long laboured under.
When wise Providence is pleased to prolong life.
He appoints means for the purpose:
may the lengthening of mine (if it be so) be to His honour, who gave it,
to which I can subjoin this desire to Him,--"`O!
may I breathe no longer than I breathe to you!`"

I can say but little as to my better part, save this,--that I am still in the warfare,
and have had of late sore struggles with some of
the old inhabitants in the promised land,
which yet remain unsubdued: but I hope by that precious faith,
which is the gift of God to the saints, to wax valiant in fight against them.
But of this excellent gift the enemy of my happiness
strives to deprive me:--may you my beloved in Christ,
and I be helped to keep it to the end; for it is the end that crowns all,
and the crown is at the end of all things here.

What ailed your dear husband that he could not add by way of P. S.,
some humbling admonition as usual?
there was room enough in your letter.
I had like to have said, 'Brother Richard,
where are you?--an important question indeed when
proposed by a heart-searching God to the sons of Adam,
who have been placed in Paradise, that is,
a state of happiness and glorious government of themselves and of the creation,
to dress the garden of the heart,
and to keep it from all venomous beasts of prey,--an awful task indeed!

[.signed-section-closing]
I am, your real friend,

[.signed-section-signature]
Mary Peisley

--

In the second month following,
she laid her intentions of marriage with Samuel
Neale before the monthly meeting of Mountmellick,
to which she belonged,
after which she found a concern to join in a visit to
the families of Friends throughout that monthly meeting.

This service she was enabled to perform;
and her friends give the following account of her last public testimony at
the next monthly meeting:--"`At our women's monthly meeting,
held at Mountmellick, the 13th of third month, 1757;
in which this our dear friend gave us her farewell visit,
which we hope will not be easily forgotten by us.
She found freedom, she said,
to speak a little of her call to the service of visiting families,
and that she met with discouragement at first by some; but afterwards,
some judicious elders and a travelling Friend encouraged her.
But the peace and comfort of her own mind in the discharge of her duty,
exceeded all she had met with in her life before.

She was drawn forth in a wonderful manner,
and often had to advise us to stand fast in this day of great
declension,--to stand fast in that liberty wherein Christ makes free,
that so we might be God's free daughters as male and female are all
one in Christ Jesus;--that we as a people were the bidden guests,
and if we make excuses too long, our excuses at length would be taken,
and then the Lord would send to the highways and hedges, and compel others to come in,
even by that which has invited us: for His table must be filled with guests.
That a glorious day would yet come,
wherein the Lord would bring from the east and from the west,
and from the north and south,
and thousands and tens of thousands would be brought to sit down with Him in His kingdom;
and that the invited unfaithful children of the kingdom would be cast out:
for the Lord was able to raise up children of them that
might be compared to the stones in the streets.

"`She also had to declare,
that she saw (and that in the light) that the fields were already white unto harvest,
and the faithful labourers but few;
so she desired that all might do their day's work in their day,
and mind the things that belong to their peace, before it should be hid from their eyes.
And she saluted a remnant, whom she desired to remember her;
that when they were absent in body, they might be present in spirit.
An extraordinary power attended her ministry and prayer,
which united the spirits of some to her in that bond of peace,
which we trust will never be broken.`"

After this visit she returned home, and on the 17th of third month, 1757,
was married to our aforesaid friend +++[+++Samuel Neale]
in the meeting of Mountrath.
+++[+++For the remarkable events of the succeeding and closing three days of her life,
the reader is referred to the Journal of Samuel Neale.]
