== Chapter IV

"`Before my leaving Ireland, I had a sight of Charleston, South Carolina,
being the port for me to land at, this continued until I returned to London,
when I lost sight of it,
which made me willingly conclude I might go with some Friends I was nearly united to,
for Philadelphia; and accordingly I went on board some vessels bound for that port,
but could not see my way in any of them.
On more deeply centring to the Root of life, in humble resignation to the Divine will,
I found it my duty to continue some weeks at London;
the not being clear of that city was, I believe,
the cause of my not seeing my way clear to Charleston,
I therefore concluded to stay the Lord`'s time, and when I found my spirit clear,
took my passage with my dear companion Catharine Payton, for that port.
Before my leaving London, I had a large and comfortable farewell meeting at the Peel;
for which my soul, with many more,
had renewed cause to bless and praise the name of the Lord.
Several Friends accompanied us from London to Portsmouth,
where we took shipping and landed at Charleston.
We had a favourable passage, save hard weather towards the latter part of the voyage;
but by the infinite mercy of Almighty God,
we were preserved from any terror or amazement,
and our health continued beyond expectation,
save the sickness occasioned by the sea and heat.
We had meetings on board every first-day,
when ability of body and the weather would permit;
which the passengers and ship`'s crew attended,
to whom the way of life and salvation was declared;
but many of their hearts being hardened through the deceitfulness of sin,
the word had not that entrance, which could have been desired.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To her sister Rachel Peisley

[.signed-section-context-open]
On board the Alexandria, 1753.

[.salutation]
Dear Sister,

As thou hast been of late frequently brought to my remembrance,
with the rest of my family, I take this opportunity to salute thee by a few lines,
heartily wishing thy welfare every way; may this find thee in true peace of mind,
health of body,
and in the pursuit of the knowledge and favour of thy great and good Creator.

I heard by letters from father,
of thy being but poorly in thy health for some time after I left you,
and again of thy being recovered or better; which I was glad of, with this proviso,
that thou might improve thy time to the glory of Him who gave thee a being,
and lengthened thy days for that purpose,
if thou art spared yet a little longer:--I say a little longer,
for it is but a short season till we must all be numbered to the silent grave.
May we therefore, while time is afforded, learn that point of great wisdom,
which the Lord our God willed to find in his people in former ages,
when He speaks after this moving manner by the mouth of
His servant,--"`O! that my people were wise,
that they understood this, that they would consider their latter end.`"
For what purpose were they to consider it,
but that they might be fitted for it by a life of purity and piety?
Remember, dear sister, that it is the pure in heart who shall see God to their comfort.

I have often thought of late,
that the Almighty by the dispensations of His Providence towards thee has
designed to awaken thy heart to a more lively sense of thy duty towards Him.
I believe the late trial thou hast had in the loss of a dear brother,
touched thee as to the quick,
and caused thee to consider the emptiness of all things here,
and the great advantage there is in having peace of conscience on a dying-bed.
Do not think me hard-hearted, dear child,
in reviving in thy memory this solemn afflicting scene,
which perhaps self-love may suggest to thee thou hadst better forget;
but suffer me to say, this is not answering the design of Providence;
not that I would have thee mourn as one without hope, or afflict thyself needlessly,
without a resigned will to Him who has an absolute undoubted right to
dispose of all His creatures according to His good pleasure.
But I well know, while I thus write,
that this happy resigned state of mind is a gift of the Lord`'s own preparing,
and not in our power to command; yet it is our duty to wait and pray for it,
with every other virtue or grace we stand in need of; but especially such,
as the want of, most oppresses us.
This should be the constant prayer of our hearts, till we have obtained it;
and this solicitude of spirit our Lord encourages us unto,
by divers parables and instances of His condescension in hearing and
relieving such as continued to follow and beseech Him in true faith.
In one parable He said to His followers, "`Which of you,
if a son ask bread will he give him a stone, or if he ask a fish will give him a serpent?
If you,`" said He, "`being evil, know how to give good gifts to your children,
how much more will your Heavenly Father give the Holy Spirit to them that ask Him.`"
But this asking must be with frequency and fervency of spirit,
from a sense of our want of it; otherwise our prayers will be cold, languid,
insipid and unacceptable to the Almighty.
I have considered thy natural disposition, and what weaknesses,
if not sins most easily beset thee.
I know thou hast something cheerful in thy temper, with an aptitude to converse,
both which are good if properly subjected by Truth; but remember, dear sister,
for every idle word we speak, we must give an account in the day of judgment;
and that vain talking and foolish jesting grieve that Holy Spirit,
by which we should be sealed to the day of redemption.
Let not the example of others draw thee from thy allegiance to thy Creator,
and a strict attendance to, and meditating in.
His law written in thy heart, as well as the sacred Scriptures of truth.

I conclude this with the salutes of true love to thyself and the family,
where I expect this will find thee.

[.signed-section-closing]
From thy affectionate sister,

[.signed-section-signature]
Mary Peisley

--

[.embedded-content-document.letter]
--

[.letter-heading]
To her Sister Elizabeth Peisley

[.signed-section-context-open]
On board the Alexandria, 1753.

[.salutation]
Dear Sister E. P.

As I have a little leisure at sea from other duties,
I find my mind engaged to communicate a little of that
love which I feel to flow in my heart towards thee,
from the true root of it, as well as from natural affection,
both which are united in a stronger manner than I shall attempt to set forth by my pen.
May Infinite Wisdom and Goodness condescend, in the riches of His mercy,
to continue and strengthen the bands of that love,
by drawing and keeping us in a strict close union with Him,
who is the Author and Fountain of love, light, and life; and as we abide in Him,
we shall have fellowship one with another,
and in that fellowship remember and pray for each other,
as well as sympathize one with another in our trials and afflictions,
whether of body or mind.
This, dear sister, I know thou hast been made capable of,
by the pure life of Truth being raised in thy soul;
may it be tenderly cherished in thee and me,
by strictly watching against everything that has a tendency to grieve, deaden,
or oppress this pure Seed of life;
and carefully waiting for the dew of heaven or spiritual manna,
by which it is nourished and refreshed,
as well as that Divine instruction by which we can become wise unto salvation,
please God, and bring glory to Him, which is the glorious end of our creation.
And in order that it may be so, I advise in much love,
that thou suffer not thy mind to be too eagerly or intently fixed on earthly things,
though it may be the duties of thy place and station,
which I would have thee by no means neglect,
nor do I believe thy careful diligent disposition would admit of it;
but what I wish for thee is,
that thou mayest do it as to the Lord with a single eye to His glory,
and desire to please Him in every undertaking; and that must be,
by setting Him always before thee, as David expressed it,
that he might not sin against Him.
When thy hands are employed in the lawful affairs of this life,
often lift up thy heart to the Lord,
by secret ejaculations and fervent desires for His preservation; yea, my sister,
let Him have thy whole heart: by this means thou wilt cheat the world,
if I may use the expression, and frustrate the designs of the enemy,
saying with the Church of old, "`though I sleep my heart waketh;`" that is,
though I appear not to men to pray, but am engaged in my lawful business,
yet my heart is awake to the Lord and converses with Him in heaven by prayer, meditation,
and fervent ejaculations; and whatsoever thou doest, do it not merely to please men,
further than it is thy duty so to do, but to please and honour thy great Creator;
otherwise thou wilt have no reward of thy Father which is in heaven.

I would not have thee omit seriously to peruse the Holy Scriptures of truth,
with care and attention; that so thou mayest remember, understand, and digest them,
seeing they are able to make thee wise unto salvation through faith in Christ; that is,
that thou mayest have the holy precepts contained
therein so riveted in thy mind and memory,
that they may be cast upon thy thoughts at every needful time of temptation;
in which the Holy Spirit will not fail to aid thee,
as thou art thus willing to become a co-worker with it.

It gave me much satisfaction to hear thou gave satisfaction to the family,
and that thou wast pleased with their conduct towards thee,
which led me to hope thou mayest make some
leisure time to put in practice the above advice,
otherwise it cannot properly be called a good place, that is,
further than it has a tendency to advance thee in piety and virtue:
the time will come when it will be seen to be so, if not now.

My heart has been enlarged in counsel to thee beyond my expectation;
which makes me ready to draw this pleasing conclusion,
from the openness and freedom which attend my mind whilst I write,
that thy mind will be prepared to receive it in the
same love and good-will in which it is communicated,
which I wish may ever attend both thee and me.
Need I ask any excuse from my beloved sister for writing to her so freely,
just what occurred to my mind for her?
surely no,--her Christian spirit, humility and good nature, will plead my excuse;
not doubting but that the grace of God will do even more than I can write.
May He who is able to keep thee from falling, preserve thee stedfast to the end,
and give thee an inheritance with them that are sanctified: so wisheth,
so prayeth thy affectionate sister,

[.signed-section-signature]
Mary Peisley

--

"`In Charleston the discipline was quite let fall,
and I found it my duty to endeavour to revive it.
Herein I met with open opposition and evil treatment,
especially from one of my own countrymen, who was of a libertine spirit,
and had been under the censure of Friends in his native land.
But the Lord was pleased to manifest his spirit,
so that he could not frustrate our endeavours.
In this province we met with many difficulties both of body and mind;
the former by long journeys, in a very thinly inhabited country,
through unbeaten paths in the woods, dangerous creeks and swamps;
with wild and venomous creatures around us,
and with such food and lodging as we had never been accustomed to:
yet the Lord our God was pleased to make it up to us by
His comfortable presence and good Spirit,
and to afford us the blessing of health,
at a time when the greatest part of the inhabitants
suffered severely with fevers and agues;
for which unmerited mercy my soul at this time bows in humble thanksgiving,
and returns Him the praise of His works, who is everlastingly worthy.`"

The following is part of a letter written to her uncle:

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel Judd

[.signed-section-context-open]
Mulberry-on-the-Wateree, 7th of Twelfth month, 1753.

[.salutation]
Dear Uncle,

It has dwelt on my heart for some days,
to give thee a short history of a long travel; and first,
may acquaint thee that through the matchless mercy of a
never-failing God to His poor depending children,
we have been preserved in a good degree of heahh,
at a tirne when most faces gathered paleness, through indisposition of body.
I do not remember that we have been in a house or family since we left Charleston,
but one or more were ill of a fever or ague,
so that it seems like an universal contagion which has
overspread the inhabitants of this quarter.
We came hither from Charleston, taking no meetings in the way,
except in the families where we lodged, the distance being 150 miles,
through woods and swamps, where our lives seemed in jeopardy every hour;
yet through mercy our minds were so supported above fear,
as to go on with a good degree of cheerfulness of spirit,
trusting in that holy Arm of power, which has hitherto wrought deliverance for us.
I have sat down by a brook in the woods, ate my Indian corn bread,
and drank water out of a calabash,
with more content and peace of mind than many who were served in plate, etc,;
and at night have slept contentedly in my riding clothes,
on a bed hard enough to make my bones ache,
and the house so open on every side as to admit plenty of light and air.
We have such variation from heat to cold in the weather,
as must of necessity be exceedingly hurtful to the constitutions of the inhabitants:
for my part I cannot but esteem it next to a miracle that our health is continued to us.
I have compared my passage through these woods to my pilgrimage through the world,
and indeed in some things it bears a just resemblance.
The path we rode through was exceedingly narrow,
and sometimes so closed as not to allow a footstep to be seen before me,
and caught by boughs on one hand, and bushes on the other, obliged to stoop very low,
lest my head or eyes should be hurt.
This I compare to the entangling things of the present world,
which are ready to catch the affections on every side, and blind the eyes of the soul;
my clothes are a little ragged by these pulls, but through care not quite torn off.

Oh! saith my soul, may I not be wholly`' stripped of the white robe,
which is the righteousness of saints;
for surely I have never been in more danger than now;
the sense of which leads me earnestly to desire,
that I may have a place in the remembrance of those,
whose prayers ascend with acceptance to the throne of grace.
I have not given the foregoing account of my bodily hardships,
by way of complaint or murmuring; no, when I consider how much more very many,
much better than I, have suffered for the cause of religion,
and especially the good Shepherd,
who laid down His life for His sheep,--every cause of complaint is removed;
remembering that the disciple is not above his Master, nor the servant above his Lord.
Yea, it is cause of rejoicing to my soul,
when I can find my feet in the footsteps of the tribulated flocks,
who trod this narrow and tried path to eternal blessedness.
In this way of life I am exempt from many dangerous temptations,
which ease and supineness are inlets to.
On my hard bed,
I am free from the fault of wasting too much of
my time in a state of inactivity and death.
At my plain meals, I am freed from many of the temptations and evils,
which attend high and voluptuous living;
and am often made to remember that excellent advice of
a great apostle to his son in the faith,
"`endure hardness, as a good soldier of Jesus Christ.`"
And surely such as are sent out to war before the face of their enemies,
may expect it in an especial manner.
But what above all other considerations,
reconciles me to every dispensation of Providence, is,
the sight and sense which Truth gives me of my own
unworthiness of the least of all the mercies I receive,
either spiritual or temporal; for indeed I see myself to be so exceedingly weak,
and capable of so little service, as not to merit the meanest food that is set before me,
yet have never been suffered to doubt, but that I am in my place,
in coming here:--but my great fear is, lest I should not keep my place in the Truth,
now I am here; seeing so many things to draw me from it.
I hope if thou or any of my friends have any word of exhortation or encouragement for me,
you will not withhold, but let me have it freely.

I think it very long to hear from my friends and family,
having been of late a little tossed,
especially in the night by dreams about my father`'s family and some others;
whether it be the work of the enemy to perplex my mind,
or a foresight of the worst of trials,
(except the loss of the favour of heaven) I cannot tell:
but when I am assisted to look beyond this transitory scene of uncertainty,
I can welcome tribulations, and rejoice in such adversities,
as have the least tendency to draw my mind nearer unto God;
which I well know must be by being weaned and
redeemed from earth and earthly satisfactions.
Alas! while I carry about with me this frail tabernacle,
its affections and desires will bend towards its original dust,
when from under the immediate influence of that holy Power,
which alone can redeem it from the thraldom of sin and Satan.
What need then have I,
and all who have been made partakers of the powers of the world to come, humbly,
diligently,
and chastely to wait for the enlightening and enlivening incomes thereof to our souls,
that so we may go on to perfection!

I have hitherto passed over our exercises in Charleston.
It seems like a city of refuge for the disjointed members of our Society,
where they may walk in the sight of their own eyes,
and the imagination of their own hearts,
without being accountable to any for their conduct,
and yet be called by the name of Quaker, to take away their reproach.
We did not meet with one in that place that kept to the plain language,
except one young man.
We lodged at the house of one that had married out of the Society,
which we went to with fear and reluctance, having first tried all means to avoid it.
Here we were greatly straitened;
but I think we were providentially cast there for his wife`'s sake,
who is under convincement, a tender-hearted, good-natured woman,
and exceedingly kind to us; and he well esteemed for a fair reputable trader.
He received us with much civility and hospitality, which yet did not blind our eyes,
or prevent our telling him the truth; I have gone so far as to acquaint him,
that I was ashamed to walk the streets with one under our name,
who deviated so much from our principles as he did; which he always took well,
and would acknowledge his faults.

We were often visited by those of other societies,
and had much kindness showed us by them.
We had freedom to make a few visits amongst them,
and had service for our Master in some of their families.
We likewise paid a religious visit to every family professing with us, in that place,
and had very close work, but with the most authority of any service we have entered on;
and by this and such like labour, I understand we have driven several from the meeting,
who could not bear sound doctrine, though ever so private.
Whether there be any sound members added, by our labour, must at present be left;
however that be, I say.
Amen, to these leaving the profession, whose lives and conduct are a scandal to it,
and I wish to be made more and more instrumental, in the hand of my God,
for division in the Society, between the precious and the vile;
let me as a creature suffer what I may, by evil report and false brethren,
which I have had, and still expect a large share of, in the way my Master leads me;
for of a truth it was His Spirit, if ever I knew it, and not my own,
that led me to this close work.
One appeared in open opposition, at a meeting appointed for conference,
in order to take steps for reviving the discipline amongst them;
he attacked me in particular, but I had then little to say to him, and what I did say,
was in great mildness; he arose in a violent passion and left the room;
since which we have seen no more of him at meeting or elsewhere.

[.signed-section-signature]
Mary Peisly

--

Her account thus continues:

"`At Neuse, in North Carolina, we had a large and comfortable meeting,
in which I thought it might be truly said the Lord`'s power was over all;
and that even devilish spirits were made subject to that power,
by which we were assisted to speak.
In this province likewise, we met with abundant hardships and sufferings of body,
as we were drawn in the love of God, to visit many of the back inhabitants,
where I suppose, no European had ever been on the like errand,
by lodging in the woods in cold frosty weather, on damp ground with bad firing.
I got a rheumatic pain in my jaws and head, by which I suffered much,
and often lost my rest after hard travelling, yet through it all,
the Lord was pleased to support my spirit in a good degree of cheerfulness,
without murmuring or repining;
though my weak constitution often deeply felt the effects of those bodily hardships:
yet by the goodness and healing virtue of the Lord,
I was often made to forget my bodily infirmities,
and to see and feel that His strength was made perfect in weakness.

"`Between Pedee and Newgarden, where is a large tract of country,
we rode two days and a half, and lay two nights in the woods,
without being under the roof of a house.
In these parts I seemed to have a hope that Truth might yet spread;
because many of the people showed a love and esteem for Friends,
and a dislike to the priests.
We were often kindly entertained, according to their ability,
at the houses of those not of our Society,
though sometimes at our first entrance they would look strangely at us,
because they understood not the lawfulness of women`'s preaching,
having never heard any,--thus did we pass for a sign and wonder; some would say,
when invited to meeting, that we were women who ran from our own country,
for some ill act,--not being acquainted with the supernatural power of love,
which had influenced our hearts, nor the rules and discipline of Friends.
Through Divine favour I have not heard of any of them who went away dissatisfied,
from meeting; may the praise of all the Lord`'s works be rendered to Himself,
who alone is worthy.

"`In the upper part of this province (North
Carolina) there is a large body of professors,
and I hope some valuable Friends; but too many I fear,--yea,
I think I sensibly felt,--are trusting in a profession,
without a possession of the living virtue of Truth.
We were at their quarterly meeting, which was large;
but the power of Truth was somewhat low, at least in me,
who suffered much under a loose unsanctified spirit.
My companion had the chief service in the public meetings, and was led, I believe,
to speak pretty much to the state of the Society;
my chief labour was in the meeting of ministers and elders,
in which we endeavoured to strive for some regulation in the discipline,
particularly that they might have their meetings for business select,
and not set open for the people,
which they were then in the practice of The weighty part of Friends joined us,
and seemed to conclude they would strive for an amendment.
I also proposed their holding a meeting for the elders to confer in,
before the ministers joined them,
in order to their hearing a more full and perfect
account of the state of the ministry in each meeting,
and to have them both held before the quarterly meeting.
This was agreed to, and the meeting ended in a lively sense of Divine love,
which makes true unity and concord amongst brethren, for which my soul was thankful.
I laboured with considerable openness at several of the particular meetings,
before the quarterly meeting;
my companion being gone on a visit southward of these parts, as far as Bath-town.`"

"`In this journey she had the trial of having a woman Friend,
who accompanied her from Perquimons, removed by death;
her remains were brought to her husband and children,
in eleven days from the time she left home, being then well to all appearance.
We attended at her funeral, which was on the whole solid and satisfactory,
though somewhat interrupted by one, who as he thought, would preach the burial sermon.
From thence we passed to Virginia,
and found things in the south-side exceedingly weak and low, the meetings very small,
and in many places the discipline sadly let fall; Friends were very kind and hospitable,
but from the poor seasons we had in spirit,
their hospitality sometimes lost its true relish yet there is a seed in these parts,
with whom my spirit had true unity.
We spent near two months in this colony, in much inward suffering,
and under some bodily hardships,
their way of living differing from what we had been accustomed to.
One thing which Friends here, as well as in North Carolina, Maryland,
and some other parts of America, were in the practice of, gave us considerable pain,
and we apprehended was in part the cause of Truth`'s not prospering amongst them,
as otherwise it would, that is, buying and keeping of slaves;
which we could not reconcile with the golden rule of
doing unto all men as we would they should do unto us.

"`At West River, Maryland,
I was concerned to write an epistle to the
yearly meeting to be held at Curies in Virginia,
which had been on my mind for some time, my companion united therewith,
and subscribed her name to said epistle, which was as follows:

[.embedded-content-document.letter]
--

[.blurb]
=== To the living, solid remnant of Friends, at the Yearly Meeting, to be held at Curles, for the colony of Virginia, in the sixth month, 1754, and especially such as Constitute the Select Meeting.

[.salutation]
Dear Friends,

In a good degree of that universal, unchangeable, enlarging love,
which drew us from our native land, and near enjoyments, to make you a religious visit,
do we at this time tenderly salute you, and hereby inform you,
as we have done some of you heretofore verbally, that our hearts have been pained,
on account of the state of the Church in your colony.
And though we cannot accuse ourselves of withholding any thing from you,
either in public or private, which was given us to deliver,
we apprehend it our duty to stir up in your remembrance, some truths already known,
and we hope, weightily felt by some of you.

First, we recommend to your solid consideration, when solemnly assembled,
the exceedingly low state of the ministry and discipline in most, if not all,
the monthly meetings in your colony.
Sink down to the pure gift of God in yourselves:--ask of Him,
with a sincere desire to be informed,--Lord,
what is the cause that we flee before our enemies, and are taken captive by them?
for thus we believe it is with some, whether they are sensible of it or not;
and as this is the case, we hope and believe, the Lord will let some of you see,
and feel, that the shortness has not been on His side,
and that He has not forsaken His people, but they Him;
and who will also give power to amend your ways and your doings.
For we cannot--we dare not suppose,
let our spirits be clothed with ever so much Christian charity,
that all who have been called, and even initiated into the true Church,
have stood faithful, and kept a single eye to the glory of God; no, no,
if that had been the case,
what a bright shining people would you have been ere this day,--yea,
as a city set upon an hill,
whose light would have diffused itself to those who were without,
and have caused many to flock to our Zion for rest and safety, as doves to the windows,
and not as birds of prey to tear and devour, as is now too much the case.
For we fear many come in amongst you with unsanctified spirits,
to make a profession of the Truth, which is now easy,
without a possession or sure inheritance in it; in which increase of number,
some have seemed to glory,
when in truth they have but increased ungodliness in the Church,
by adding chaff instead of the solid, weighty wheat,
which alone will be gathered into the Lord`'s garner; but the chaff of all kinds,
will be burnt with unquenchable fire.
Where then will these light, chaffy unsanctified professors appear,
or what will they add to you,
except it be an incumbrance and a clog to the small handful of solid Friends amongst you,
who we believe are too much oppressed and borne down, yea, who He as hid and buried,
under this light windy spirit.

Arise, we beseech you, in the name and power of your God, and exert yourselves,
in His pure wisdom and strength, for His cause and Truth on earth.
Victory is on the Lord`'s side, and will be yours, if you faithfully follow Him,
in the way of His requirings; and not fearing the faces of men,
but strictly regarding the still,
small voice and gentle motions of the blessed Spirit of Truth.
As this is the case, one shall chase a thousand of these light frothy spirits,
and two put ten thousand to flight; though you may, yea, must,
be little and low in your own eyes.
And we earnestly desire, that such as have been called to,
and in some measure qualified for, the work of the Lord,
and through a desire of some kind or other of filthy lucre, of which there are many,
are become formal, blind and unfaithful, may repent,
and do their first works,--seeing from whence they are
fallen,--lest the Lord come to them quickly,
and remove such candlestick out of its place;
whose candles are already put out by the baneful breath of the spirit of this world,
with which they have universally mingled, and in which they are held captive.
Arise from this state, if possible, and shake yourselves from the dust of the earth,
with which some of you are laden, as with thick clay.
But if you are so benumbed, hardened and stupified, through the deceitfulness of sin,
that this cannot be, yet cease at least to pervert the right way of the Lord,
by meddling in things with which you have no business, that is,
putting yourselves forth in the ministry or discipline, when Christ the true Shepherd,
has not put forth therein.
Remember what befel him, who stretched forth a hand to the ark,
even when it tottered and seemed in danger of falling;
the same event will happen to the spiritual lives of all those,
who continue for a series of time,
to mock and deceive themselves and the people
with a sound of words without life or power,
which however sound in themselves and well connected, are but as a dead letter,
which kills instead of quickening the soul.
Let this certain self-evident truth be weightily considered by you, viz.,
that nothing but life and light should move to act in the church of Christ;
not pity for the people, nor inclination to gratify their longing desire after words,
nor any other human passion or consideration, should move us thus to tempt the Lord,
and take His holy name in vain, in the worst sense of the expressions;
for those who do so.
He has declared He will not hold guiltless.

And dear Friends,
we apprehend that a great part of the weakness and
unfruitfulness which appears in the ministry amongst you,
proceeds from a want of a right sound discipline,
established and conducted in the wisdom of Truth;
which discipline is certainly not only as a wall of defence
against the encroachments of many dangerous enemies,
but is as a hedge to shelter from the various baneful blasts,
destructive to young and tender plants, which should be sheltered as well as watered,
primed and dug about, by wise judicious elders or fathers and mothers in the church.
But alas! how do the few who are on the right foundation, stand as alone,
exposed to the darts of their enemies, and to piercing blasts from every side, unpruned,
and in a great degree unadvised; can such be expected to bring forth plentiful crops,
of full, ripe, well flavoured fruit?
Nay, rather the savour of the wild grape is to be feared,
because the trees are left in a great measure without cultivation.

Now as the hedge is thus sadly taken away, and the wall greatly broken down,
we are sensible the reparation must be by gradual steps, yea,
by laying a single stone at a time, and planting a tender twig.
And those who are engaged in this necessary work, will find,
as Nehemiah did before he went to repair the walls of Jerusalem, sadness of countenance,
ere they can entreat the Almighty for liberty to engage in the work.
Nothing short of a heart truly touched with love
and zeal for the good of the Church of Christ,
can adopt this language, "`Here am I, send me;`"--or, "`Qualify me and let me go.`"
May it be yours, O! ye beloved tender plants of the Lord`'s right hand planting;
and when it is, stifle it not, but go on in the strength of the Lord, not saying,
"`Here am I, and I will go in the strength of my own spirit, will or wisdom.`"
No, we give our testimony for our Lord and Master, that these forward unsavoury spirits,
will never profit the people, nor bring glory to God.
But you who are of the former rank, though thou may meet with many discouragements,
as Nehemiah did, yet if ye trust in the Lord with all your hearts,
and singly eye His light in yourselves, not conferring with flesh and blood,
nor seeking your own honour, but the honour of Him who sent you into life;
it is our testimony to you, for your encouragement,
that the Lord will bless His work in your hands, and richly reward you for it,
though you may have a long and painful travail, and sometimes as in the night season,
before you come at the right place for building; and when you come there,
you will find much rubbish to be removed.
This we apprehend must be the first work,
before one stone can be properly laid on the right foundation, i,
e+++.+++ to have all unsanctified spirits, both of your own and other societies,
excluded the privilege of sitting in your meetings for business;
otherwise we believe it will be building with the rubbish,
which will never stand to the honour of God and the good of his people.

Our minds are so sensibly affected with the pernicious tendency of that evil custom,
of suffering your meetings for the discipline of the Church to be thus mixed, that,
believing it to be the mind of Truth,
we cannot help advising that you use your Christian endeavours for an alteration,
by making a minute against this disorderly practice,
and strongly recommending the putting of it in force in
the several monthly meetings throughout the colony;
for which you have authority from the universal practice of
Friends where the discipline is rightly conducted,
as well as from the original institution of such meetings.

And now having in a good degree eased our spirits of
what seemed to rest upon them on your account,
we conclude in that love which seeks the preservation and good of the heritage of God,
and exhort you to be sober, be vigilant, and of one mind;
and desiring that the God of peace may be with you in this your annual assembly,
we remain your friends in the Truth.

[.signed-section-signature]
Mary Peisley & Catherine Payton

[.signed-section-context-close]
West River, in Maryland, the 4th of the Fifth month, 1754

--

"`At this meeting of Friends at West River,
we were falsely accused of speaking from outward information,--when in truth it was
from the opening of the word of life,--this we were frequently suspected of,
and charged with, by unbelievers, who knew not the intelligence of the Spirit,
though they made professions of it.

"`We passed through the western side of Maryland, called Sassafras bay,
and took meetings in our way; but after entering Pennsylvania,
we had no openness to appoint meetings in that province, the Jerseys, or Long Island,
except one; but we passed on in a pretty direct line,
falling in with some meetings as they came in course, till we got to Rhode Island,
the day before the yearly meeting: this was held at Newport.
It was large, and was attended with a good degree of Divine power, peace, and concord.
At this meeting we found our minds engaged to
labour for some regulations in the discipline,
which was sadly out of order; in particular,
that unwise practice of having meetings for discipline mixed with the world`'s people,
and such as were proper subjects to have it exercised upon,
which seemed to be the first step necessary to be taken.
We prevailed so far as to have a minute made against it,
and sent to the several quarterly and monthly meetings,
as the result of the yearly meeting; this gave us an opportunity as we fell in with them,
to strengthen Friends in having their meetings select.

"`It was remarkable that we fell in with so many
of them in the course of our labour and service,
I write this for my own instruction and that of others,
as an incitement to follow the leading of Truth and the way it points out to us,
though the cause may not immediately appear,
and indeed on all accounts I have seen it best so to do.

"`One mark of providential care, which occurred in this journey,
is I think worthy of remembrance; when at New York, some Friends of that city and others,
seemed inclined that we should go by water to Newport,
in a sloop that was to sail next day; accordingly we went to view the vessel,
and found her very small and inconvenient, having no cabin that we could well sit, stand,
or lie in.
They seemed to think we might make our passage in twenty-four, or at most,
forty-eight hours.
We sat down quietly in her, to feel if there was freedom in the Truth for us to go,
a practice I like to be adopted on such occasions; when it appeared to me,
that if we sailed in her,
we should meet with greater difficulties than if we went by land to South-hold,
and thence to Newport by water.
I told Friends that I had more freedom to go by land, and they readily agreed to it:
we went as proposed, and had some meetings to good satisfaction,
amongst the Presbyterians at and near South-hold,
and fell in with a small meeting of Friends in the way,
having also some seasoning opportunities among ourselves,
wherein the Divine presence was manifested to our mutual comfort.
We waited some days at South-hold for a fair wind, went on board a vessel,
and landed the same evening; the sloop which it was intended we should go in,
arrived only the same day, having been eight days on her passage from New York.

"`At Philadelphia, the 23rd of the Fifth month,
I received the sorrowful tidings of the death of my dear and tender father,
who departed this life in much peace and quietude of spirit,
on the 23rd of the Second month last,
according to the account I received from those who were present;
he having been favoured with his understanding and a sense of his change.
This was of a truth sore and hard to bear,
and I have great cause to bless and praise His great name,
who supported me under this trial beyond my expectation or desert,
as well as prepared my mind for it, by a foresight of it, both sleeping and waking.
For I saw, in a dream, my father in the agonies of death; and in the time of his illness,
day after day, I felt such a sympathy of soul as is not easily expressed; and after that,
I was sensible of a stop in my mind from thinking of or writing to him,
which convinced me that he was gone: thus I fully expected this account.

"`We attended a Quarterly meeting at Hampton in New England,
where we had to testify against an unruly separate spirit,
though we had not seen or heard of it outwardly, as I declared to them;
there was nothing to convince us of it but the Spirit of Truth;
this they would not believe, though they were high pretenders to revelation.
They abundantly convinced us, before the Quarterly meeting was over, of our being right,
for such was their outrage that they used the utmost of
their power to prevent us from speaking in the meeting,
to ease our minds, by noises both within and without the house;
but Truth gave us the victory, and set our spirits over them.
