== Chapter VI

[.blurb]
=== The Testimonies of Richard Shackleton and his wife Elizabeth, concerning Mary Neale, late Peisley.

She was a shining pattern in a solid circumspect life and conversation,
enabled to be so by following her great Pattern our Lord and Saviour Jesus Christ.
Her soul loved and sought after retirement:
she delighted in meditation on things appertaining to God`'s kingdom; and her speech,
behaviour, and manner of speaking, to an intelligent person,
would often bewray that her conversation had been with Jesus.

And as her deportment was apparently seasoned with an holy awfulness,
evincing whose presence she was in,
so it tended much to inspire others who conversed with
her with a degree of like awe and watchful fear.
She was one of great inwardness of spirit,
and diligent in giving heed to her Spiritual Guide, not only in matters purely religious,
but in concerns of a more external nature.
From this inwardness of spirit and habitual acquaintance with her own heart,
was produced a deep humility and self-abhorrence,
which were very conspicuous in her to those who knew her most intimately.

She laboured hard, travelled much, and suffered deeply in the service of Him,
who had sent her into His vineyard, and was eminently honoured and dignified beyond many;
yet she thought of herself after all but as an unprofitable servant,
who had only done what she ought,
and sat down thankful and contented with that degree of
peace which her Master was pleased to reward her with,
and was satisfied to be stripped and to want, as well as to be clothed and to abound.

Her ministry was deep,
clear and reaching her conduct and conversation were of a piece with her ministry;
her life and doctrine went hand-in-hand as becomes a minister.
She laboured faithfully according to the ability present, whether little or much,
and carefully followed the leadings of the Spirit, in the exercise of her gift,
willing as a mere instrument to be made use of as a sharp threshing weapon,
as well as a watering-pot in the hand of her Master; for she sought not to please man,
but the Lord, not courting, but shunning popular applause,
and zealously appearing against what she thought wrong in any, without respect to person;
being neither moved by the smiles or frowns of mortals,
from performing what she apprehended to be her duty,
with a single eye to the honour of her Lord and Master,--so
that she apparently had her building upon that immovable Rock,
which has been the foundation of the righteous in all generations,
and which remains to this day and forever.

[.signed-section-signature]
Richard Shackleton.

It has been on my mind, for some time,
to write a few lines concerning my knowledge of my dear deceased friend, Mary Neale,
with whom I have been nearly united and intimately acquainted for several years;
and I can say of her,
that she was a tender nurse and help-forward of
the true-born children of the heavenly Father;
for whom she could say with the Apostle, she travailed in pain,
that Christ might be formed in them, and they might be complete in Him;
by her living baptizing-ministry, which she had received from Him,
who makes His ministers as a flame of fire,
she was often made to administer consolation to such.
Those who too much neglected their own mercies,
the repeated calls of Wisdom in their hearts,
and labours of her children from one time to another,
she was often concerned to call and invite to return;
she deeply mourned in secret on their account, having seen the danger they were in,
and as one of their friends, she warned them faithfully thereof,
in order to be clear of the blood of all men.

In her conduct and conversation she was an example of steady piety and solidity;
and as she was sensible of her own insufficiency to keep them,
she was concerned to be much inward in her mind with Him,
who was more to her than all the world; and her desire was,
that she might breathe no longer than she breathed to Him.
She was a woman that sought true wisdom and found it, and who got understanding,
in which she was deep, sound in her judgment,
and skilful in speaking to the state of the auditory,
amongst whom she had the Gospel to preach,
which she was careful to adorn by a circumspect life.
Her being so suddenly taken from us,
has been the cause of sorrow on account of our great loss; but, as her work was done,
and cut short in righteousness,
and her spirit ascended to receive a happy reward for her faithful, constant, diligent,
and undaunted labours in her great Master`'s cause, we desire to be given up to His will,
and to be enabled to pray to Him, that a double portion of the same good Spirit,
that was her guide, may be poured upon others;
that there may be still witnesses to the same everlasting Power, which is unchangeable,
though all men should forsake it!

[.signed-section-signature]
Elizabeth Shackleton

[.blurb]
=== Extract from James Gough`'s Memoirs

"`We went, next day, some miles out of our way to see our dear friend, Mary Peisley,
being at that time in affliction.
She had been a gay young woman, but in the youthful years of her gaiety,
she was favored with a powerful and prevailing visitation of Divine love;
and giving up faithfully to the heavenly vision,
she became a vessel of honour in the Master`'s house, receiving a gift in the ministry,
and being reverently, watchfully, and livelily exercised therein,
to the edification of Friends, where her lot was cast,
she was indeed a useful member and a shining ornament of the Church.
I am ready to conclude, that none in our day, from the time of this,
the effectual visitation of Christ in her soul,
adhered with more steadiness to His guidance through a variety of probations.
She was, most part of her time,
a member of the same monthly meeting with myself:
--often were we together in public meetings,
often on family visits.
She visited Friends in England, Ireland and North America, pretty generally;
and soon after her return from her last journey, married our friend, Samuel Neale,
and in a few days after, departed this life.
I attended both at her marriage and her funeral,
and am satisfied that she is gone to enjoy forever the reward of a well-spent life,
very much devoted to the service of God, and the promotion of Truth upon earth.`"

[.blurb]
=== The Testimony of the Monthly meeting of Mounlmellick, in the Kingdom of Ireland, concerning our dear friend Mary Neale, formerly Peisley, deceased.

She was educated in our Christian profession, yet,
in her younger years was a lover of gayety and vanity;
till it pleased the Lord to enlighten and enamour her
soul with the beauty of His blessed and glorious Truth,
whereupon she gave herself up to serve Him with full purpose of heart.

Being called into the work of the ministry, she readily obeyed, yet with fear,
being particularly careful not to be too forward;
so that her offerings were like fruit in its right season,
to the honour of the Lord and the consolation of His heritage;
yet she rather feared than sought applause, was ready to give way to others,
and rejoiced when the Lord`'s work was well done by any.
She was a diligent labourer in spirit for the
subjection of self and the prevalence of Divine Life;
and as she was very careful, when a necessity was laid upon her,
to raise up in that Life, so she was likewise to drop anchor, and sit down in it,
more delighted in the pure silence of all flesh,
and to hear the voice of her Beloved therein, than in any excellency of words;
the reverent solidity and patience of her own
waiting upon the Lord in religious meetings,
being like a check to the forward, as well as a good pattern to the believers in general,
both in a public and private capacity.
She was, when out of meetings, of an uniform conduct, retired in spirit,
awful and weighty in her deportment; her words few and savoury,
administering grace to the hearers, consolation to the feeble-minded,
instruction to the ignorant, and reproof to the unfaithful;
seeking much to have her conversation in heaven,
and on every occasion to draw the minds of others thitherward.
In Friends`' families often drawn forth in the pure love of God, particularly to the youth.

In the discipline of the church, of singular service, waiting for wisdom to discern,
and fortitude to support, what tended to Zion`'s order, peace, and prosperity;
not biased by the favour or frowns of any therein,
so that (though but young as to the time of her ministry and
services) she stood in the authority of Truth,
like an elder and a pillar in the Lord`'s house, bearing the weight of opposition,
and assaults of opposite spirits without giving way; that Divine Power being her shield,
and the munition of rocks the habitation of her soul.

Under a lively concern for the welfare and honour of every part of the Society, she was,
at times qualified to impart tender and suitable
counsel to her brethren and sisters engaged,
in these perilous times, in the weighty work of the ministry and discipline,
to have a single eye to the glory of God, to prefer His service before their own,
and get their day`'s work well done in the day-time.
In this, she freely gave up herself to spend and be spent,
and to pass through various perils of the nearest and most exercising kind,
by sea and land, often under great weakness and hardship of body,
as well as pain of mind.
Twice she visited the meetings of Friends through this nation; once through England,
and since that, through the American continent: and by accounts received,
we find her services abroad corresponded with the testimony here given of her.

Since her return from her American journey, she, with some others,
visited the families of Friends through the nine meetings of this Monthly meeting,
as she had done awhile before her said journey.
The weight of that service laid chiefly upon her,
and we believe she discharged herself faithfully therein.
It was finished on the 14th of the third month last; and on the 20th, she was,
after an illness of about fourteen hours,
removed by death to the sorrowful surprise of many,
in a sense both of our own loss and that of the Church in general,
in the sudden removal of this worthy instrument in the Lord`'s hand who, we believe,
was well prepared to live with Christ in His kingdom,
with whom her life was hid whilst here.
She was, indeed, a true burden-bearer, a valiant warrior,
that turned not her back in the day of battle,
very nearly united in the celestial bond to such as loved Truth above all things;
and has left very few amongst us like her,
in respect to faithful and diligent application
to the great and primary end of our existence.

On the 24th of the said month, her corpse was taken into the meeting-house in Mountrath,
where a solemn meeting was held on the occasion, and several testimonies borne,
many Friends from adjacent meetings attending;
after which it was decently interred in Friends burying-ground in the said town.
She died aged 39 years, a minister about twelve years and six months.
We conclude, with fervent desires,
that the sense and remembrance of her life and labours,
may stir up her survivors to follow her as she followed Christ,
in that holy path which none but the redeemed can walk in,
(there never having been more need than now when the church is
greatly stript of bright ornaments and useful instruments,
and when so many are indulging themselves in undue liberties,)
that in the revival and increase of righteousness,
the Name of our God may be glorified, who is worthy both now and forever.
Amen!

[.signed-section-closing]
Signed in, and on behalf of our Monthly Men`'s and Women`'s meeting,
held at Mountmellick, the 1st of fifth month, 1757,

[.signed-section-signature]
By fifty Friends.
